In [ ]:
import pandas as pd
df = pd.read_csv(r"..\Data_in\survey_results_public_2025.csv",low_memory=False)

In [2]:
df .head(30)

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
5,6,I am a developer by profession,45-54 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc....",15.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,GitHub Copilot,NaN,When I have ethical or security concerns about...,designing the architecture in the new domain,120000.0,7.0
6,7,I am a developer by profession,25-34 years old,Some college/university study without earning ...,"Independent contractor, freelancer, or self-em...",None of the above,9.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,Sentry,NaN,ChatGPT;Claude Code;Google Gemini,NaN,When I don’t trust AI’s answers;When I need he...,NaN,6240.0,6.0
7,8,I am a developer by profession,35-44 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Employed,Engaged in paid work (20-29 hours per week);Tr...,22.0,"Yes, I am not new to coding but am learning ne...",Books / Physical media;Technical documentation...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I want to learn best practices;When I wan...,"Innovation, system design",72000.0,6.0
8,9,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc....",9.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70000.0,8.0
9,10,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,7.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","No, I learned something that was not related t...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I’m stuck and can’t explain the problem;W...,NaN,5400.0,4.0
10,11,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,7.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,Spring AI,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Microsoft C...,NaN,When I don’t trust AI’s answers;When I have et...,Code writing. I know this sounds weird but you...,65691.0,10.0
11,12,I am a developer by profession,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,3.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I need qu...,NaN,14400.0,8.0
12,13,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",10.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"No, I learned something that was not related t...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I want to fully understand something;When...,NaN,1099.0,7.0
13,14,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc.)",6.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
14,15,I am a developer by profession,35-44 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Employed,Attending school (full-time);Attending school ...,15.0,"No, I am not new to coding and did not learn n...",NaN,"No, I learned something that was not related t...",...,NaN,NaN,NaN,NaN,NaN,NaN,I don’t think I’ll need help from people anymore,senior development,NaN,9.0
15,16,I am a developer by profession,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Student,Engaged in paid work (20-29 hours per week);En...,5.0,"Yes, I am new to coding or currently a student",Online Courses or Certification (includes all ...,"No, I learned something that was not related t...",...,Vertex AI;Agno;AutoGen (Microsoft);CrewAI;IBM ...,NaN,Galileo;Honeycomb;Metero;New Relic;opik;Snyk,NaN,ChatGPT;AgentGPT;Auto-GPT;Devin AI;Glean (Ente...,NaN,When I don’t trust AI’s answers;When I have et...,5,NaN,7.0
16,17,"I am not primarily a developer, but I write co...",65 years or older,Some college/university study without earning ...,Retired,None of the above,20.0,"No, I am not new to coding and did not learn n...",NaN,"No, I didn't spend time learning in the past year",...,NaN,NaN,NaN,NaN,NaN,NaN,Other (please specify):,All the ones that INTELLIGENT programmers curr...,16252.0,NaN
17,18,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,NaN,1.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I want to learn best practices;When I hav...,NaN,NaN,6.0
18,19,I am a developer by profession,35-44 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,20.0,"Yes, I am not new to coding but am learning ne...",Stack Overflow or Stack Exchange;Technical doc...,"No, I didn't spend time learning in the past year",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,AI will not become more capable in 3-5 years.,NaN,5.0
19,20,"I am not primarily a developer, but I write co...",25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",Engaged in paid work (less than 10 hours per w...,3.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,I don’t think I’ll need help from people anymore,Research,NaN,NaN
20,21,"I am not primarily a developer, but I write co...",55-64 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Employed,None of the above,40.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","No, I learned something that was not related t...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,22,"I am not primarily a developer, but I write co...",45-54 years old,Some college/university study without earning ...,Employed,None of the above,35.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","No, I didn't spend time learning in the past year",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,interacting with people,NaN,NaN
22,23,I am a developer by profession,25-34 years old,Some college/university study without earning ...,Employed,None of the above,7.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Technical knowledge. As AI slides into the for...,87500.0,9.0
23,24,I am a developer by profession,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,2.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","No, I learned something that was not related t...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,"Problem solving, communication",NaN,8.0
24,25,I am a developer by profession,65 years or older,Some college/university study without earning ...,"Independent contractor, freelancer, or self-em...",Transitioning to retirement (gradually reducin...,40.0,"No, I am not new to coding and did not learn n...",NaN,"No, I learned something that was not related t...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I’m stuck...,"Real coding skills, assembler, mainframe, COBO...",NaN,9.0
25,26,I am a developer by profession,55-64 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,37.0,"Yes, I am not new to coding but am learning ne...",Stack Overflow or Stack Exchange;Technical doc...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;GitHub Copilot;Replit,NaN,When I don’t trust AI’s answers;When I want to...,Choosing the best solutions. Converting user r...,108913.0,8.0
26,27,I am a developer by profession,45-54 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",None of the above,26.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,The ability to tackle more open ended problems...,162421.0,8.0
27,28,I am a developer by profession,45-54 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc.)",24.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,NaN,209643.0,9.0
28,29,I am a developer by profession,35-44 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",Engaged in paid work (20-29 hours per week),13.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",...,Ollama,NaN,Honeycomb,NaN,ChatGPT;GitHub Copilot;Google Gemini,Cursor,When I don’t trust AI’s answers;When I want to...,"System Design, Maintainability, Common Sense",78000.0,10.0
29,30,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (10-19 hours per week),19.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Being able to make sure the AI code is correct...,205000.0,8.0

In [3]:
df.info(verbose=True)

<class 'pandas.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Data columns (total 172 columns):
 #    Column                                    Dtype
---   ------                                    -----
 0    ResponseId                                int64
 1    MainBranch                                str
 2    Age                                       str
 3    EdLevel                                   str
 4    Employment                                str
 5    EmploymentAddl                            str
 6    WorkExp                                   float64
 7    LearnCodeChoose                           str
 8    LearnCode                                 str
 9    LearnCodeAI                               str
 10   AILearnHow                                str
 11   YearsCode                                 float64
 12   DevType                                   str
 13   OrgSize                                   str
 14   ICorPM                                    str
 15   RemoteWork                                str
 16   PurchaseInfluence                         str
 17   TechEndorseIntro                          str
 18   TechEndorse_1                             float64
 19   TechEndorse_2                             float64
 20   TechEndorse_3                             float64
 21   TechEndorse_4                             float64
 22   TechEndorse_5                             float64
 23   TechEndorse_6                             float64
 24   TechEndorse_7                             float64
 25   TechEndorse_8                             float64
 26   TechEndorse_9                             float64
 27   TechEndorse_13                            float64
 28   TechEndorse_13_TEXT                       str
 29   TechOppose_1                              float64
 30   TechOppose_2                              float64
 31   TechOppose_3                              float64
 32   TechOppose_5                              float64
 33   TechOppose_7                              float64
 34   TechOppose_9                              float64
 35   TechOppose_11                             float64
 36   TechOppose_13                             float64
 37   TechOppose_16                             float64
 38   TechOppose_15                             float64
 39   TechOppose_15_TEXT                        str
 40   Industry                                  str
 41   JobSatPoints_1                            float64
 42   JobSatPoints_2                            float64
 43   JobSatPoints_3                            float64
 44   JobSatPoints_4                            float64
 45   JobSatPoints_5                            float64
 46   JobSatPoints_6                            float64
 47   JobSatPoints_7                            float64
 48   JobSatPoints_8                            float64
 49   JobSatPoints_9                            float64
 50   JobSatPoints_10                           float64
 51   JobSatPoints_11                           float64
 52   JobSatPoints_13                           float64
 53   JobSatPoints_14                           float64
 54   JobSatPoints_15                           float64
 55   JobSatPoints_16                           float64
 56   JobSatPoints_15_TEXT                      str
 57   AIThreat                                  str
 58   NewRole                                   str
 59   ToolCountWork                             float64
 60   ToolCountPersonal                         float64
 61   Country                                   str
 62   Currency                                  str
 63   CompTotal                                 float64
 64   LanguageChoice                            str
 65   LanguageHaveWorkedWith                    str
 66   LanguageWantToWorkWith                    str
 67   LanguageAdmired                           str
 68   LanguagesHaveEntry                        str
 69   LanguagesWantEntry                        str
 70   DatabaseChoice                            str
 71   DatabaseHaveWorkedWith                    str
 72   DatabaseWantToWorkWith                    str
 73   DatabaseAdmired                           str
 74   DatabaseHaveEntry                         str
 75   DatabaseWantEntry                         str
 76   PlatformChoice                            str
 77   PlatformHaveWorkedWith                    str
 78   PlatformWantToWorkWith                    str
 79   PlatformAdmired                           str
 80   PlatformHaveEntry                         str
 81   PlatformWantEntry                         str
 82   WebframeChoice                            str
 83   WebframeHaveWorkedWith                    str
 84   WebframeWantToWorkWith                    str
 85   WebframeAdmired                           str
 86   WebframeHaveEntry                         str
 87   WebframeWantEntry                         str
 88   DevEnvsChoice                             str
 89   DevEnvsHaveWorkedWith                     str
 90   DevEnvsWantToWorkWith                     str
 91   DevEnvsAdmired                            str
 92   DevEnvHaveEntry                           str
 93   DevEnvWantEntry                           str
 94   SOTagsHaveWorkedWith                      str
 95   SOTagsWantToWorkWith                      str
 96   SOTagsAdmired                             str
 97   SOTagsHaveEntry                           str
 98   SOTagsWant Entry                          str
 99   OpSysPersonal use                         str
 100  OpSysProfessional use                     str
 101  OfficeStackAsyncHaveWorkedWith            str
 102  OfficeStackAsyncWantToWorkWith            str
 103  OfficeStackAsyncAdmired                   str
 104  OfficeStackHaveEntry                      str
 105  OfficeStackWantEntry                      str
 106  CommPlatformHaveWorkedWith                str
 107  CommPlatformWantToWorkWith                str
 108  CommPlatformAdmired                       str
 109  CommPlatformHaveEntr                      str
 110  CommPlatformWantEntr                      str
 111  AIModelsChoice                            str
 112  AIModelsHaveWorkedWith                    str
 113  AIModelsWantToWorkWith                    str
 114  AIModelsAdmired                           str
 115  AIModelsHaveEntry                         str
 116  AIModelsWantEntry                         str
 117  SOAccount                                 str
 118  SOVisitFreq                               str
 119  SODuration                                str
 120  SOPartFreq                                str
 121  SO_Dev_Content                            str
 122  SO_Actions_1                              float64
 123  SO_Actions_16                             float64
 124  SO_Actions_3                              float64
 125  SO_Actions_4                              float64
 126  SO_Actions_5                              float64
 127  SO_Actions_6                              float64
 128  SO_Actions_9                              float64
 129  SO_Actions_7                              float64
 130  SO_Actions_10                             float64
 131  SO_Actions_15                             float64
 132  SO_Actions_15_TEXT                        str
 133  SOComm                                    str
 134  SOFriction                                str
 135  AISelect                                  str
 136  AISent                                    str
 137  AIAcc                                     str
 138  AIComplex                                 str
 139  AIToolCurrently partially AI              str
 140  AIToolDon't plan to use AI for this task  str
 141  AIToolPlan to partially use AI            str
 142  AIToolPlan to mostly use AI               str
 143  AIToolCurrently mostly AI                 str
 144  AIFrustration                             str
 145  AIExplain                                 str
 146  AIAgents                                  str
 147  AIAgentChange                             str
 148  AIAgent_Uses                              str
 149  AgentUsesGeneral                          str
 150  AIAgentImpactSomewhat agree               str
 151  AIAgentImpactNeutral                      str
 152  AIAgentImpactSomewhat disagree            str
 153  AIAgentImpactStrongly agree               str
 154  AIAgentImpactStrongly disagree            str
 155  AIAgentChallengesNeutral                  str
 156  AIAgentChallengesSomewhat disagree        str
 157  AIAgentChallengesStrongly agree           str
 158  AIAgentChallengesSomewhat agree           str
 159  AIAgentChallengesStrongly disagree        str
 160  AIAgentKnowledge                          str
 161  AIAgentKnowWrite                          str
 162  AIAgentOrchestration                      str
 163  AIAgentOrchWrite                          str
 164  AIAgentObserveSecure                      str
 165  AIAgentObsWrite                           str
 166  AIAgentExternal                           str
 167  AIAgentExtWrite                           str
 168  AIHuman                                   str
 169  AIOpen                                    str
 170  ConvertedCompYearly                       float64
 171  JobSat                                    float64
dtypes: float64(52), int64(1), str(119)
memory usage: 64.6 MB

In [4]:
list(df.columns)

['ResponseId',
 'MainBranch',
 'Age',
 'EdLevel',
 'Employment',
 'EmploymentAddl',
 'WorkExp',
 'LearnCodeChoose',
 'LearnCode',
 'LearnCodeAI',
 'AILearnHow',
 'YearsCode',
 'DevType',
 'OrgSize',
 'ICorPM',
 'RemoteWork',
 'PurchaseInfluence',
 'TechEndorseIntro',
 'TechEndorse_1',
 'TechEndorse_2',
 'TechEndorse_3',
 'TechEndorse_4',
 'TechEndorse_5',
 'TechEndorse_6',
 'TechEndorse_7',
 'TechEndorse_8',
 'TechEndorse_9',
 'TechEndorse_13',
 'TechEndorse_13_TEXT',
 'TechOppose_1',
 'TechOppose_2',
 'TechOppose_3',
 'TechOppose_5',
 'TechOppose_7',
 'TechOppose_9',
 'TechOppose_11',
 'TechOppose_13',
 'TechOppose_16',
 'TechOppose_15',
 'TechOppose_15_TEXT',
 'Industry',
 'JobSatPoints_1',
 'JobSatPoints_2',
 'JobSatPoints_3',
 'JobSatPoints_4',
 'JobSatPoints_5',
 'JobSatPoints_6',
 'JobSatPoints_7',
 'JobSatPoints_8',
 'JobSatPoints_9',
 'JobSatPoints_10',
 'JobSatPoints_11',
 'JobSatPoints_13',
 'JobSatPoints_14',
 'JobSatPoints_15',
 'JobSatPoints_16',
 'JobSatPoints_15_TEXT',
 'AIThreat',
 'NewRole',
 'ToolCountWork',
 'ToolCountPersonal',
 'Country',
 'Currency',
 'CompTotal',
 'LanguageChoice',
 'LanguageHaveWorkedWith',
 'LanguageWantToWorkWith',
 'LanguageAdmired',
 'LanguagesHaveEntry',
 'LanguagesWantEntry',
 'DatabaseChoice',
 'DatabaseHaveWorkedWith',
 'DatabaseWantToWorkWith',
 'DatabaseAdmired',
 'DatabaseHaveEntry',
 'DatabaseWantEntry',
 'PlatformChoice',
 'PlatformHaveWorkedWith',
 'PlatformWantToWorkWith',
 'PlatformAdmired',
 'PlatformHaveEntry',
 'PlatformWantEntry',
 'WebframeChoice',
 'WebframeHaveWorkedWith',
 'WebframeWantToWorkWith',
 'WebframeAdmired',
 'WebframeHaveEntry',
 'WebframeWantEntry',
 'DevEnvsChoice',
 'DevEnvsHaveWorkedWith',
 'DevEnvsWantToWorkWith',
 'DevEnvsAdmired',
 'DevEnvHaveEntry',
 'DevEnvWantEntry',
 'SOTagsHaveWorkedWith',
 'SOTagsWantToWorkWith',
 'SOTagsAdmired',
 'SOTagsHaveEntry',
 'SOTagsWant Entry',
 'OpSysPersonal use',
 'OpSysProfessional use',
 'OfficeStackAsyncHaveWorkedWith',
 'OfficeStackAsyncWantToWorkWith',
 'OfficeStackAsyncAdmired',
 'OfficeStackHaveEntry',
 'OfficeStackWantEntry',
 'CommPlatformHaveWorkedWith',
 'CommPlatformWantToWorkWith',
 'CommPlatformAdmired',
 'CommPlatformHaveEntr',
 'CommPlatformWantEntr',
 'AIModelsChoice',
 'AIModelsHaveWorkedWith',
 'AIModelsWantToWorkWith',
 'AIModelsAdmired',
 'AIModelsHaveEntry',
 'AIModelsWantEntry',
 'SOAccount',
 'SOVisitFreq',
 'SODuration',
 'SOPartFreq',
 'SO_Dev_Content',
 'SO_Actions_1',
 'SO_Actions_16',
 'SO_Actions_3',
 'SO_Actions_4',
 'SO_Actions_5',
 'SO_Actions_6',
 'SO_Actions_9',
 'SO_Actions_7',
 'SO_Actions_10',
 'SO_Actions_15',
 'SO_Actions_15_TEXT',
 'SOComm',
 'SOFriction',
 'AISelect',
 'AISent',
 'AIAcc',
 'AIComplex',
 'AIToolCurrently partially AI',
 "AIToolDon't plan to use AI for this task",
 'AIToolPlan to partially use AI',
 'AIToolPlan to mostly use AI',
 'AIToolCurrently mostly AI',
 'AIFrustration',
 'AIExplain',
 'AIAgents',
 'AIAgentChange',
 'AIAgent_Uses',
 'AgentUsesGeneral',
 'AIAgentImpactSomewhat agree',
 'AIAgentImpactNeutral',
 'AIAgentImpactSomewhat disagree',
 'AIAgentImpactStrongly agree',
 'AIAgentImpactStrongly disagree',
 'AIAgentChallengesNeutral',
 'AIAgentChallengesSomewhat disagree',
 'AIAgentChallengesStrongly agree',
 'AIAgentChallengesSomewhat agree',
 'AIAgentChallengesStrongly disagree',
 'AIAgentKnowledge',
 'AIAgentKnowWrite',
 'AIAgentOrchestration',
 'AIAgentOrchWrite',
 'AIAgentObserveSecure',
 'AIAgentObsWrite',
 'AIAgentExternal',
 'AIAgentExtWrite',
 'AIHuman',
 'AIOpen',
 'ConvertedCompYearly',
 'JobSat']

In [5]:
df.shape

(49191, 172)

In [6]:
ai_col=[col for col in df.columns if "ai" in col.lower()]
ai_col

['MainBranch',
 'LearnCodeAI',
 'AILearnHow',
 'AIThreat',
 'AIModelsChoice',
 'AIModelsHaveWorkedWith',
 'AIModelsWantToWorkWith',
 'AIModelsAdmired',
 'AIModelsHaveEntry',
 'AIModelsWantEntry',
 'AISelect',
 'AISent',
 'AIAcc',
 'AIComplex',
 'AIToolCurrently partially AI',
 "AIToolDon't plan to use AI for this task",
 'AIToolPlan to partially use AI',
 'AIToolPlan to mostly use AI',
 'AIToolCurrently mostly AI',
 'AIFrustration',
 'AIExplain',
 'AIAgents',
 'AIAgentChange',
 'AIAgent_Uses',
 'AIAgentImpactSomewhat agree',
 'AIAgentImpactNeutral',
 'AIAgentImpactSomewhat disagree',
 'AIAgentImpactStrongly agree',
 'AIAgentImpactStrongly disagree',
 'AIAgentChallengesNeutral',
 'AIAgentChallengesSomewhat disagree',
 'AIAgentChallengesStrongly agree',
 'AIAgentChallengesSomewhat agree',
 'AIAgentChallengesStrongly disagree',
 'AIAgentKnowledge',
 'AIAgentKnowWrite',
 'AIAgentOrchestration',
 'AIAgentOrchWrite',
 'AIAgentObserveSecure',
 'AIAgentObsWrite',
 'AIAgentExternal',
 'AIAgentExtWrite',
 'AIHuman',
 'AIOpen']

In [7]:
Keyword=[
    "age",
    "employe",
    "learn",
    "work",
    "country",
    "Platform",
    "Language",
    "databse",
    "ai",
    "year",
    "dev",
    "tool"
]
for col in df.columns:
    for k in Keyword:
        if k.lower() in col.lower():
            print(col)
            break

MainBranch
Age
WorkExp
LearnCodeChoose
LearnCode
LearnCodeAI
AILearnHow
YearsCode
DevType
RemoteWork
AIThreat
ToolCountWork
ToolCountPersonal
Country
LanguageChoice
LanguageHaveWorkedWith
LanguageWantToWorkWith
LanguageAdmired
LanguagesHaveEntry
LanguagesWantEntry
DatabaseHaveWorkedWith
DatabaseWantToWorkWith
PlatformChoice
PlatformHaveWorkedWith
PlatformWantToWorkWith
PlatformAdmired
PlatformHaveEntry
PlatformWantEntry
WebframeHaveWorkedWith
WebframeWantToWorkWith
DevEnvsChoice
DevEnvsHaveWorkedWith
DevEnvsWantToWorkWith
DevEnvsAdmired
DevEnvHaveEntry
DevEnvWantEntry
SOTagsHaveWorkedWith
SOTagsWantToWorkWith
OfficeStackAsyncHaveWorkedWith
OfficeStackAsyncWantToWorkWith
CommPlatformHaveWorkedWith
CommPlatformWantToWorkWith
CommPlatformAdmired
CommPlatformHaveEntr
CommPlatformWantEntr
AIModelsChoice
AIModelsHaveWorkedWith
AIModelsWantToWorkWith
AIModelsAdmired
AIModelsHaveEntry
AIModelsWantEntry
SO_Dev_Content
AISelect
AISent
AIAcc
AIComplex
AIToolCurrently partially AI
AIToolDon't plan to use AI for this task
AIToolPlan to partially use AI
AIToolPlan to mostly use AI
AIToolCurrently mostly AI
AIFrustration
AIExplain
AIAgents
AIAgentChange
AIAgent_Uses
AgentUsesGeneral
AIAgentImpactSomewhat agree
AIAgentImpactNeutral
AIAgentImpactSomewhat disagree
AIAgentImpactStrongly agree
AIAgentImpactStrongly disagree
AIAgentChallengesNeutral
AIAgentChallengesSomewhat disagree
AIAgentChallengesStrongly agree
AIAgentChallengesSomewhat agree
AIAgentChallengesStrongly disagree
AIAgentKnowledge
AIAgentKnowWrite
AIAgentOrchestration
AIAgentOrchWrite
AIAgentObserveSecure
AIAgentObsWrite
AIAgentExternal
AIAgentExtWrite
AIHuman
AIOpen
ConvertedCompYearly

In [8]:
df.head(30)

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
5,6,I am a developer by profession,45-54 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc....",15.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,GitHub Copilot,NaN,When I have ethical or security concerns about...,designing the architecture in the new domain,120000.0,7.0
6,7,I am a developer by profession,25-34 years old,Some college/university study without earning ...,"Independent contractor, freelancer, or self-em...",None of the above,9.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,Sentry,NaN,ChatGPT;Claude Code;Google Gemini,NaN,When I don’t trust AI’s answers;When I need he...,NaN,6240.0,6.0
7,8,I am a developer by profession,35-44 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Employed,Engaged in paid work (20-29 hours per week);Tr...,22.0,"Yes, I am not new to coding but am learning ne...",Books / Physical media;Technical documentation...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I want to learn best practices;When I wan...,"Innovation, system design",72000.0,6.0
8,9,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc....",9.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70000.0,8.0
9,10,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,7.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","No, I learned something that was not related t...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I’m stuck and can’t explain the problem;W...,NaN,5400.0,4.0
10,11,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,7.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,Spring AI,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Microsoft C...,NaN,When I don’t trust AI’s answers;When I have et...,Code writing. I know this sounds weird but you...,65691.0,10.0
11,12,I am a developer by profession,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,3.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I need qu...,NaN,14400.0,8.0
12,13,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",10.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"No, I learned something that was not related t...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I want to fully understand something;When...,NaN,1099.0,7.0
13,14,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc.)",6.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
14,15,I am a developer by profession,35-44 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Employed,Attending school (full-time);Attending school ...,15.0,"No, I am not new to coding and did not learn n...",NaN,"No, I learned something that was not related t...",...,NaN,NaN,NaN,NaN,NaN,NaN,I don’t think I’ll need help from people anymore,senior development,NaN,9.0
15,16,I am a developer by profession,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Student,Engaged in paid work (20-29 hours per week);En...,5.0,"Yes, I am new to coding or currently a student",Online Courses or Certification (includes all ...,"No, I learned something that was not related t...",...,Vertex AI;Agno;AutoGen (Microsoft);CrewAI;IBM ...,NaN,Galileo;Honeycomb;Metero;New Relic;opik;Snyk,NaN,ChatGPT;AgentGPT;Auto-GPT;Devin AI;Glean (Ente...,NaN,When I don’t trust AI’s answers;When I have et...,5,NaN,7.0
16,17,"I am not primarily a developer, but I write co...",65 years or older,Some college/university study without earning ...,Retired,None of the above,20.0,"No, I am not new to coding and did not learn n...",NaN,"No, I didn't spend time learning in the past year",...,NaN,NaN,NaN,NaN,NaN,NaN,Other (please specify):,All the ones that INTELLIGENT programmers curr...,16252.0,NaN
17,18,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,NaN,1.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I want to learn best practices;When I hav...,NaN,NaN,6.0
18,19,I am a developer by profession,35-44 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,20.0,"Yes, I am not new to coding but am learning ne...",Stack Overflow or Stack Exchange;Technical doc...,"No, I didn't spend time learning in the past year",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,AI will not become more capable in 3-5 years.,NaN,5.0
19,20,"I am not primarily a developer, but I write co...",25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",Engaged in paid work (less than 10 hours per w...,3.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,I don’t think I’ll need help from people anymore,Research,NaN,NaN
20,21,"I am not primarily a developer, but I write co...",55-64 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Employed,None of the above,40.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","No, I learned something that was not related t...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,22,"I am not primarily a developer, but I write co...",45-54 years old,Some college/university study without earning ...,Employed,None of the above,35.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","No, I didn't spend time learning in the past year",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,interacting with people,NaN,NaN
22,23,I am a developer by profession,25-34 years old,Some college/university study without earning ...,Employed,None of the above,7.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Technical knowledge. As AI slides into the for...,87500.0,9.0
23,24,I am a developer by profession,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,2.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","No, I learned something that was not related t...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,"Problem solving, communication",NaN,8.0
24,25,I am a developer by profession,65 years or older,Some college/university study without earning ...,"Independent contractor, freelancer, or self-em...",Transitioning to retirement (gradually reducin...,40.0,"No, I am not new to coding and did not learn n...",NaN,"No, I learned something that was not related t...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I’m stuck...,"Real coding skills, assembler, mainframe, COBO...",NaN,9.0
25,26,I am a developer by profession,55-64 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,37.0,"Yes, I am not new to coding but am learning ne...",Stack Overflow or Stack Exchange;Technical doc...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;GitHub Copilot;Replit,NaN,When I don’t trust AI’s answers;When I want to...,Choosing the best solutions. Converting user r...,108913.0,8.0
26,27,I am a developer by profession,45-54 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",None of the above,26.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,The ability to tackle more open ended problems...,162421.0,8.0
27,28,I am a developer by profession,45-54 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc.)",24.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,NaN,209643.0,9.0
28,29,I am a developer by profession,35-44 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",Engaged in paid work (20-29 hours per week),13.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",...,Ollama,NaN,Honeycomb,NaN,ChatGPT;GitHub Copilot;Google Gemini,Cursor,When I don’t trust AI’s answers;When I want to...,"System Design, Maintainability, Common Sense",78000.0,10.0
29,30,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (10-19 hours per week),19.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Being able to make sure the AI code is correct...,205000.0,8.0

In [9]:
general_info_col=[
    "Age",
    "Country",
    "Employment",
    "MainBranch",
    "AISelect",
    "AISent",
    "AIAcc",
    "AIComplex",
    "AIAgents"
]
for col in general_info_col:
    if col in df.columns:
        print("\n")
        print("="*50)
        print(df[col].value_counts(dropna=False).head(20))

==================================================
Age
25-34 years old      16519
35-44 years old      13241
18-24 years old       9210
45-54 years old       6275
55-64 years old       2626
65 years or older      942
Prefer not to say      378
Name: count, dtype: int64


==================================================
Country
NaN                                                     13754
United States of America                                 7233
Germany                                                  3025
India                                                    2547
United Kingdom of Great Britain and Northern Ireland     2042
France                                                   1409
Canada                                                   1305
Ukraine                                                   964
Poland                                                    888
Netherlands                                               867
Italy                                                     835
Brazil                                                    825
Australia                                                 804
Spain                                                     717
Sweden                                                    616
Switzerland                                               546
Czech Republic                                            520
Austria                                                   410
Romania                                                   323
Belgium                                                   321
Name: count, dtype: int64


==================================================
Employment
Employed                                                33750
Independent contractor, freelancer, or self-employed     6708
Student                                                  4428
Not employed                                             2227
NaN                                                       852
Retired                                                   708
I prefer not to say                                       518
Name: count, dtype: int64


==================================================
MainBranch
I am a developer by profession                                                                37467
I am not primarily a developer, but I write code sometimes as part of my work/studies          4894
I am learning to code                                                                          2585
I code primarily as a hobby                                                                    1924
I used to be a developer by profession, but no longer am                                       1325
I work with developers or my work supports developers but am not a developer by profession      996
Name: count, dtype: int64


==================================================
AISelect
Yes, I use AI tools daily                      15883
NaN                                            15471
Yes, I use AI tools weekly                      5958
No, and I don't plan to                         5454
Yes, I use AI tools monthly or infrequently     4628
No, but I plan to soon                          1797
Name: count, dtype: int64


==================================================
AISent
NaN                 15724
Favorable           12311
Very favorable       7677
Indifferent          5880
Unfavorable          3621
Very unfavorable     3219
Unsure                759
Name: count, dtype: int64


==================================================
AIAcc
NaN                           15894
Somewhat trust                 9869
Somewhat distrust              8685
Neither trust nor distrust     7162
Highly distrust                6533
Highly trust                   1048
Name: count, dtype: int64


==================================================
AIComplex
NaN                                                      15908
Good, but not great at handling complex tasks             8384
Bad at handling complex tasks                             7328
Very poor at handling complex tasks                       5844
I don't use AI tools for complex tasks / I don't know     5582
Neither good or bad at handling complex tasks             4688
Very well at handling complex tasks                       1457
Name: count, dtype: int64


==================================================
AIAgents
NaN                                                      17272
No, and I don't plan to                                  12082
No, but I plan to                                         5561
Yes, I use AI agents at work daily                        4509
No, I use AI exclusively in copilot/autocomplete mode     4401
Yes, I use AI agents at work weekly                       2868
Yes, I use AI agents at work monthly or infrequently      2498
Name: count, dtype: int64

In [10]:
important_cols = [
    'Age',
    'Country',
    'Employment',
    'MainBranch',
    'AISelect',
    'AISent',
    'AIAcc',
    'AIComplex',
    'AIAgents'
]

df_clean = df[important_cols].copy()

df_clean['Age'] = df_clean['Age'].fillna('Unknown')
df_clean['Country'] = df_clean['Country'].fillna('Unknown Country')
df_clean['Employment'] = df_clean['Employment'].fillna('Unknown')
df_clean['MainBranch'] = df_clean['MainBranch'].fillna('Unknown')

for col in ['AISelect', 'AISent', 'AIAcc', 'AIComplex', 'AIAgents']:
    df_clean[col] = df_clean[col].fillna('No Response')

In [11]:
general_info_col_clean=[
    "Age",
    "Country",
    "Employment",
    "MainBranch",
    "AISelect",
    "AISent",
    "AIAcc",
    "AIComplex",
    "AIAgents"
]
for col in general_info_col:
    if col in df_clean.columns:
        print("\n")
        print("="*50)
        print(df_clean[col].value_counts(dropna=False).head(20))

==================================================
Age
25-34 years old      16519
35-44 years old      13241
18-24 years old       9210
45-54 years old       6275
55-64 years old       2626
65 years or older      942
Prefer not to say      378
Name: count, dtype: int64


==================================================
Country
Unknown Country                                         13754
United States of America                                 7233
Germany                                                  3025
India                                                    2547
United Kingdom of Great Britain and Northern Ireland     2042
France                                                   1409
Canada                                                   1305
Ukraine                                                   964
Poland                                                    888
Netherlands                                               867
Italy                                                     835
Brazil                                                    825
Australia                                                 804
Spain                                                     717
Sweden                                                    616
Switzerland                                               546
Czech Republic                                            520
Austria                                                   410
Romania                                                   323
Belgium                                                   321
Name: count, dtype: int64


==================================================
Employment
Employed                                                33750
Independent contractor, freelancer, or self-employed     6708
Student                                                  4428
Not employed                                             2227
Unknown                                                   852
Retired                                                   708
I prefer not to say                                       518
Name: count, dtype: int64


==================================================
MainBranch
I am a developer by profession                                                                37467
I am not primarily a developer, but I write code sometimes as part of my work/studies          4894
I am learning to code                                                                          2585
I code primarily as a hobby                                                                    1924
I used to be a developer by profession, but no longer am                                       1325
I work with developers or my work supports developers but am not a developer by profession      996
Name: count, dtype: int64


==================================================
AISelect
Yes, I use AI tools daily                      15883
No Response                                    15471
Yes, I use AI tools weekly                      5958
No, and I don't plan to                         5454
Yes, I use AI tools monthly or infrequently     4628
No, but I plan to soon                          1797
Name: count, dtype: int64


==================================================
AISent
No Response         15724
Favorable           12311
Very favorable       7677
Indifferent          5880
Unfavorable          3621
Very unfavorable     3219
Unsure                759
Name: count, dtype: int64


==================================================
AIAcc
No Response                   15894
Somewhat trust                 9869
Somewhat distrust              8685
Neither trust nor distrust     7162
Highly distrust                6533
Highly trust                   1048
Name: count, dtype: int64


==================================================
AIComplex
No Response                                              15908
Good, but not great at handling complex tasks             8384
Bad at handling complex tasks                             7328
Very poor at handling complex tasks                       5844
I don't use AI tools for complex tasks / I don't know     5582
Neither good or bad at handling complex tasks             4688
Very well at handling complex tasks                       1457
Name: count, dtype: int64


==================================================
AIAgents
No Response                                              17272
No, and I don't plan to                                  12082
No, but I plan to                                         5561
Yes, I use AI agents at work daily                        4509
No, I use AI exclusively in copilot/autocomplete mode     4401
Yes, I use AI agents at work weekly                       2868
Yes, I use AI agents at work monthly or infrequently      2498
Name: count, dtype: int64

In [12]:
adoption_map = {
    'Yes, I use AI tools daily':'Daily User',
    'Yes, I use AI tools weekly':'Weekly User',
    'Yes, I use AI tools monthly or infrequently':'Occasional User',
    'No, but I plan to soon':'Future User',
    "No, and I don't plan to":'Non User',
    'No Response':'No Response'
}

df_clean['AI_Usage_Group'] = df_clean['AISelect'].map(adoption_map)

In [13]:
sentiment_map = {
    'Very favorable':'Positive',
    'Favorable':'Positive',
    'Indifferent':'Neutral',
    'Unsure':'Neutral',
    'Unfavorable':'Negative',
    'Very unfavorable':'Negative',
    'No Response':'No Response'
}

df_clean['Sentiment_Group'] = df_clean['AISent'].map(sentiment_map)

In [14]:
trust_map = {
    'Highly trust':'Trust',
    'Somewhat trust':'Trust',
    'Neither trust nor distrust':'Neutral',
    'Somewhat distrust':'Distrust',
    'Highly distrust':'Distrust',
    'No Response':'No Response'
}

df_clean['Trust_Group'] = df_clean['AIAcc'].map(trust_map)

In [15]:
complexity_map = {
    'Very well at handling complex tasks':'Good',
    'Good, but not great at handling complex tasks':'Good',
    'Neither good or bad at handling complex tasks':'Neutral',
    'Bad at handling complex tasks':'Poor',
    'Very poor at handling complex tasks':'Poor',
    "I don't use AI tools for complex tasks / I don't know":'Unknown',
    'No Response':'No Response'
}

df_clean['AI_Capability_Group'] = df_clean['AIComplex'].map(complexity_map)

In [16]:
agent_map = {
    'Yes, I use AI agents at work daily':'Active User',
    'Yes, I use AI agents at work weekly':'Active User',
    'Yes, I use AI agents at work monthly or infrequently':'Active User',
    'No, but I plan to':'Future User',
    "No, and I don't plan to":'Non User',
    'No, I use AI exclusively in copilot/autocomplete mode':'Copilot Only',
    'No Response':'No Response'
}

df_clean['Agent_Adoption_Group'] = df_clean['AIAgents'].map(agent_map)

In [17]:
 for col in df_clean.columns:
    print("\n" + "="*50)
    print(df_clean[col].value_counts().head(30))

==================================================
Age
25-34 years old      16519
35-44 years old      13241
18-24 years old       9210
45-54 years old       6275
55-64 years old       2626
65 years or older      942
Prefer not to say      378
Name: count, dtype: int64

==================================================
Country
Unknown Country                                         13754
United States of America                                 7233
Germany                                                  3025
India                                                    2547
United Kingdom of Great Britain and Northern Ireland     2042
France                                                   1409
Canada                                                   1305
Ukraine                                                   964
Poland                                                    888
Netherlands                                               867
Italy                                                     835
Brazil                                                    825
Australia                                                 804
Spain                                                     717
Sweden                                                    616
Switzerland                                               546
Czech Republic                                            520
Austria                                                   410
Romania                                                   323
Belgium                                                   321
Denmark                                                   316
Israel                                                    297
Turkey                                                    295
Mexico                                                    286
Portugal                                                  280
China                                                     255
New Zealand                                               255
Finland                                                   254
South Africa                                              253
Greece                                                    252
Name: count, dtype: int64

==================================================
Employment
Employed                                                33750
Independent contractor, freelancer, or self-employed     6708
Student                                                  4428
Not employed                                             2227
Unknown                                                   852
Retired                                                   708
I prefer not to say                                       518
Name: count, dtype: int64

==================================================
MainBranch
I am a developer by profession                                                                37467
I am not primarily a developer, but I write code sometimes as part of my work/studies          4894
I am learning to code                                                                          2585
I code primarily as a hobby                                                                    1924
I used to be a developer by profession, but no longer am                                       1325
I work with developers or my work supports developers but am not a developer by profession      996
Name: count, dtype: int64

==================================================
AISelect
Yes, I use AI tools daily                      15883
No Response                                    15471
Yes, I use AI tools weekly                      5958
No, and I don't plan to                         5454
Yes, I use AI tools monthly or infrequently     4628
No, but I plan to soon                          1797
Name: count, dtype: int64

==================================================
AISent
No Response         15724
Favorable           12311
Very favorable       7677
Indifferent          5880
Unfavorable          3621
Very unfavorable     3219
Unsure                759
Name: count, dtype: int64

==================================================
AIAcc
No Response                   15894
Somewhat trust                 9869
Somewhat distrust              8685
Neither trust nor distrust     7162
Highly distrust                6533
Highly trust                   1048
Name: count, dtype: int64

==================================================
AIComplex
No Response                                              15908
Good, but not great at handling complex tasks             8384
Bad at handling complex tasks                             7328
Very poor at handling complex tasks                       5844
I don't use AI tools for complex tasks / I don't know     5582
Neither good or bad at handling complex tasks             4688
Very well at handling complex tasks                       1457
Name: count, dtype: int64

==================================================
AIAgents
No Response                                              17272
No, and I don't plan to                                  12082
No, but I plan to                                         5561
Yes, I use AI agents at work daily                        4509
No, I use AI exclusively in copilot/autocomplete mode     4401
Yes, I use AI agents at work weekly                       2868
Yes, I use AI agents at work monthly or infrequently      2498
Name: count, dtype: int64

==================================================
AI_Usage_Group
Daily User         15883
No Response        15471
Weekly User         5958
Non User            5454
Occasional User     4628
Future User         1797
Name: count, dtype: int64

==================================================
Sentiment_Group
Positive       19988
No Response    15724
Negative        6840
Neutral         6639
Name: count, dtype: int64

==================================================
Trust_Group
No Response    15894
Distrust       15218
Trust          10917
Neutral         7162
Name: count, dtype: int64

==================================================
AI_Capability_Group
No Response    15908
Poor           13172
Good            9841
Unknown         5582
Neutral         4688
Name: count, dtype: int64

==================================================
Agent_Adoption_Group
No Response     17272
Non User        12082
Active User      9875
Future User      5561
Copilot Only     4401
Name: count, dtype: int64

In [18]:
df_clean.to_csv(
    'AI_Adoption_2025_Clean.csv',
    index=False
)

In [49]:
pd.set_option('display.max_columns', None)
df.head(30)

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;...,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);DALL-E;OpenAI,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,NaN,No,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,NaN,NaN,Yes,Datadog;Firebase;npm;pnpm,Amazon Web Services (AWS);Firebase;npm;pnpm;Vite,Firebase;npm;pnpm,NaN,NaN,Yes,Next.js;Node.js;React,Next.js;Node.js;React,Next.js;Node.js;React,NaN,Solid.js,Yes,Visual Studio Code,Visual Studio Code;Windsurf,Visual Studio Code,NaN,NaN,Google Gemini,Google Gemini;Shadcn/ui,Google Gemini,NaN,NaN,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,NaN,NaN,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,NaN,NaN,Yes,Gemini (Flash general purpose models);openAI G...,Gemini (Flash general purpose models);Gemini (...,Gemini (Flash general purpose models);openAI G...,NaN,NaN,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year",Chat (people);Videos;Lists of recommendations ...,3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...,NaN,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Generat...,NaN,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,NaN,NaN,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,NaN,10.0,5.0,8.0,4.0,13.0,12.0,2.0,7.0,1.0,15.0,NaN,Retail and Consumer Services,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,NaN,NaN,Ukraine,EUR European Euro,31200.0,Yes,Java;Kotlin;SQL,Java;Kotlin,Java;Kotlin,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Amazon Bedrock,NaN,NaN,NaN,NaN,Windows,Windows;Ubuntu,GitLab;Jira;Miro,GitLab;Jira,GitLab;Jira,NaN,NaN,Stack Overflow;Reddit;YouTube;LinkedIn,"Stack Overflow;Reddit;GitHub (public projects,...",Stack Overflow;Reddit;YouTube;LinkedIn,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Videos;Chat (bot/AI),1.0,NaN,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,NaN,Project planning;Documenting code;Testing code...,Learning about a codebase;Writing code;Debuggi...,Search for answers;Generating content or synth...,NaN,"AI solutions that are almost right, but not qu...",NO,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about n...,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,22.0,Engineering manager,NaN,NaN,NaN,"Yes, I endorsed a tool that was open-source an...",Work,6.0,3.0,1.0,9.0,10.0,8.0,7.0,4.0,2.0,14.0,NaN,7.0,13.0,3.0,9.0,12.0,6.0,1.0,8.0,14.0,15.0,NaN,Software Development,9.0,4.0,11.0,13.0,14.0,8.0,6.0,5.0,7.0,2.0,1.0,12.0,10.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,4.0,3.0,Ukraine,USD United States dollar,60000.0,Yes,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...,C#;Java;JavaScript;Python;SQL;TypeScript,C#;Java;JavaScript;Python;SQL;TypeScript,NaN,NaN,Yes,Elasticsearch;Microsoft SQL Server;MySQL;Oracl...,Elasticsearch;Oracle;PostgreSQL,Elasticsearch;Oracle;PostgreSQL,NaN,NaN,Yes,Amazon Web Services (AWS);APT;Docker;Make;Mave...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,NaN,NaN,Yes,Angular;ASP.NET;ASP.NET Core;Flask;jQuery,Angular;ASP.NET Core;Flask,Angular;ASP.NET Core;Flask,NaN,NaN,Yes,Eclipse;IntelliJ IDEA;Jupyter Notebook/Jupyter...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,NaN,NaN,Large Language Model;Google Gemini,Large Language Model,Large Language Model,NaN,NaN,Windows;iOS,Windows;Ubuntu;Debian,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,NaN,NaN,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,No,A few times per month or weekly,Between 5 and 10 years,"Infrequently, less than once per year",Long-form articles,1.0,NaN,7.0,4.0,2.0,5.0,10.0,6.0,12.0,15.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debuggi...,Project planning;Documenting code;Testing code...,Generating content or synthetic data,NaN,NaN,"AI solutions that are almost right, but not quite",partly,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,It takes significant time and effort to learn ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
5,6,I am a developer by profession,45-54 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc....",15.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",Technical documentation (is generated for/by t...,20.0,"Developer, back-end",NaN,NaN,NaN,"Yes, I influenced the purchase of a substantia...",Work,12.0,5.0,4.0,6.0,2.0,10.0,3.0,7.0,8.0,14.0,NaN,12.0,5.0,13.0,10.0,9.0,1.0,4.0,6.0,2.0,15.0,NaN,Fintech,4.0,3.0,5.0,8.0,9.0,2.0,1.0,10.0,11.0,12.0,6.0,13.0,14.0,15.0,7.0,NaN,I'm not sure,I have somewhat considered changing my career ...,5.0,5.0,Ukraine,USD United States dollar,120000.0,Yes,Java;Scala,Java;Kotlin;Scala,Java;Scala,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Google Cloud;Microso...,Amazon Web Services (AWS),Amazon Web Services (AWS),NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,akka,akka,Yes,IntelliJ IDEA;Visual Studio Code,IntelliJ IDEA;Visual Studio Code,IntelliJ IDEA;Visual Studio Code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MacOS,MacOS,Azure Devops;GitHub;GitLab;Jira,GitHub;Jira,GitHub;Jira,NaN,NaN,Stack Overflow;Stack Exchange;X;YouTube;Linked...,Stack Overflow;Stack Exchange;X;YouTube;Linked...,Stack Overflow;Stack Exchange;X;YouTube;Linked...,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 10 and 15 years,"Infrequently, less than once per year","Lists of recommendations (tools, frameworks, t...",6.0,NaN,9.0,3.0,4.0,5.0,10.0,1.0,11.0,15.0,NaN,"Yes, somewhat","Rarely, almost never","Yes, I use AI tools daily",Indifferent,Somewhat distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Documen...,Predictive analytics,Deployment and monitoring,Project planning;Debugging or fixing code;Comm...,Testing code;Learning new concepts or technolo...,"AI solutions that are almost right, but not quite",No it isnt,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering;Business process automati...,NaN,AI agents have increased my productivity.;AI a...,NaN,AI agents have improved the quality of my code...,AI agents have helped me automate repetitive t...,NaN,The cost of using certain AI agent platforms i...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,My company's IT and/or InfoSec teams have stri...,NaN,NaN,NaN,NaN,NaN,NaN,GitHub Copilot,NaN,When I have ethical or security concerns about...,designing the architecture in the new domain,120000.0,7.0

In [34]:
columns = [
    'AIModelsHaveWorkedWith',
    'AIModelsWantToWorkWith',
    'AIModelsAdmired'
]

for col in columns:
    print(f"\n=== {col} ===")
    
    counts = (
        df[col]
        .dropna()
        .str.split(';')
        .explode()
        .str.strip()
        .value_counts()
    )
    
    print(counts)

=== AIModelsHaveWorkedWith ===
AIModelsHaveWorkedWith
openAI GPT (chatbot models)              13424
Claude                                    7063
Gemini (Flash general purpose models)     5823
OpenAI Reasoning                          5716
DALL-E                                    4395
Gemini (Pro Reasoning models)             4221
DeepSeek (R- Reasoning models)            3848
Meta Llama (all models)                   2941
DeepSeek (V- General purpose models)      2363
Grok                                      1839
Mistral                                   1712
Perplexity                                1250
Qwen                                       864
Phi-4                                      833
Titan                                      283
Command A                                  139
Reka (Flash 3 or other Reka models)         57
Name: count, dtype: int64

=== AIModelsWantToWorkWith ===
AIModelsWantToWorkWith
openAI GPT (chatbot models)              8328
Claude                                   5428
OpenAI Reasoning                         4213
Gemini (Flash general purpose models)    3865
Gemini (Pro Reasoning models)            3670
DALL-E                                   3031
DeepSeek (R- Reasoning models)           2750
Meta Llama (all models)                  2004
DeepSeek (V- General purpose models)     1832
Grok                                     1429
Mistral                                  1288
Perplexity                               1012
Qwen                                      669
Phi-4                                     629
Titan                                     312
Command A                                 155
Reka (Flash 3 or other Reka models)       131
Name: count, dtype: int64

=== AIModelsAdmired ===
AIModelsAdmired
openAI GPT (chatbot models)              8219
Claude                                   4767
OpenAI Reasoning                         3631
Gemini (Flash general purpose models)    3294
Gemini (Pro Reasoning models)            2751
DALL-E                                   2610
DeepSeek (R- Reasoning models)           1980
Meta Llama (all models)                  1419
DeepSeek (V- General purpose models)     1211
Grok                                      955
Mistral                                   849
Perplexity                                685
Qwen                                      465
Phi-4                                     356
Titan                                     121
Command A                                  58
Reka (Flash 3 or other Reka models)        35
Name: count, dtype: int64

In [39]:
model_mapping = {
    "openAI GPT (chatbot models)": "OpenAI",
    "openAI Reasoning models": "OpenAI",
    "openAI Image generating models": "OpenAI",
    "OpenAI Reasoning": "OpenAI",

    "Anthropic: Claude Sonnet": "Claude",

    "Gemini (Flash general purpose models)": "Gemini",
    "Gemini (Pro Reasoning models)": "Gemini",

    "DeepSeek (R- Reasoning models)": "DeepSeek",
    "DeepSeek (V- General purpose models)": "DeepSeek",

    "Meta Llama (all models)": "Llama",
    "X Grok models": "Grok",
    "Mistral AI models": "Mistral",
    "Perplexity Sonar models": "Perplexity",
    "Alibaba Cloud Qwen models": "Qwen",
    "Microsoft Phi-4 models": "Phi-4",
    "Amazon Titan models": "Titan",
    "Cohere: Command A": "Command A",
    "Reka (Flash 3 or other Reka models)": "Reka"
}

In [51]:
columns = [
    "AIModelsHaveWorkedWith",
    "AIModelsWantToWorkWith",
    "AIModelsAdmired"
]

for col in columns:
    for old, new in model_mapping.items():
        df[col] = df[col].str.replace(old, new, regex=False)

In [52]:
pd.set_option('display.max_columns', None)
df.head(30)

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;...,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,OpenAI;DALL-E;OpenAI,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,NaN,NaN,Yes,OpenAI,OpenAI,OpenAI,NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,NaN,No,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,NaN,NaN,Yes,Datadog;Firebase;npm;pnpm,Amazon Web Services (AWS);Firebase;npm;pnpm;Vite,Firebase;npm;pnpm,NaN,NaN,Yes,Next.js;Node.js;React,Next.js;Node.js;React,Next.js;Node.js;React,NaN,Solid.js,Yes,Visual Studio Code,Visual Studio Code;Windsurf,Visual Studio Code,NaN,NaN,Google Gemini,Google Gemini;Shadcn/ui,Google Gemini,NaN,NaN,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,NaN,NaN,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,NaN,NaN,Yes,Gemini;OpenAI,Gemini;Gemini;OpenAI,Gemini;OpenAI,NaN,NaN,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year",Chat (people);Videos;Lists of recommendations ...,3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...,NaN,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Generat...,NaN,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,NaN,NaN,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,NaN,10.0,5.0,8.0,4.0,13.0,12.0,2.0,7.0,1.0,15.0,NaN,Retail and Consumer Services,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,NaN,NaN,Ukraine,EUR European Euro,31200.0,Yes,Java;Kotlin;SQL,Java;Kotlin,Java;Kotlin,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Amazon Bedrock,NaN,NaN,NaN,NaN,Windows,Windows;Ubuntu,GitLab;Jira;Miro,GitLab;Jira,GitLab;Jira,NaN,NaN,Stack Overflow;Reddit;YouTube;LinkedIn,"Stack Overflow;Reddit;GitHub (public projects,...",Stack Overflow;Reddit;YouTube;LinkedIn,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Videos;Chat (bot/AI),1.0,NaN,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,NaN,Project planning;Documenting code;Testing code...,Learning about a codebase;Writing code;Debuggi...,Search for answers;Generating content or synth...,NaN,"AI solutions that are almost right, but not qu...",NO,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about n...,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,22.0,Engineering manager,NaN,NaN,NaN,"Yes, I endorsed a tool that was open-source an...",Work,6.0,3.0,1.0,9.0,10.0,8.0,7.0,4.0,2.0,14.0,NaN,7.0,13.0,3.0,9.0,12.0,6.0,1.0,8.0,14.0,15.0,NaN,Software Development,9.0,4.0,11.0,13.0,14.0,8.0,6.0,5.0,7.0,2.0,1.0,12.0,10.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,4.0,3.0,Ukraine,USD United States dollar,60000.0,Yes,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...,C#;Java;JavaScript;Python;SQL;TypeScript,C#;Java;JavaScript;Python;SQL;TypeScript,NaN,NaN,Yes,Elasticsearch;Microsoft SQL Server;MySQL;Oracl...,Elasticsearch;Oracle;PostgreSQL,Elasticsearch;Oracle;PostgreSQL,NaN,NaN,Yes,Amazon Web Services (AWS);APT;Docker;Make;Mave...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,NaN,NaN,Yes,Angular;ASP.NET;ASP.NET Core;Flask;jQuery,Angular;ASP.NET Core;Flask,Angular;ASP.NET Core;Flask,NaN,NaN,Yes,Eclipse;IntelliJ IDEA;Jupyter Notebook/Jupyter...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,NaN,NaN,Large Language Model;Google Gemini,Large Language Model,Large Language Model,NaN,NaN,Windows;iOS,Windows;Ubuntu;Debian,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,NaN,NaN,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,NaN,NaN,Yes,OpenAI,OpenAI,OpenAI,NaN,NaN,No,A few times per month or weekly,Between 5 and 10 years,"Infrequently, less than once per year",Long-form articles,1.0,NaN,7.0,4.0,2.0,5.0,10.0,6.0,12.0,15.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debuggi...,Project planning;Documenting code;Testing code...,Generating content or synthetic data,NaN,NaN,"AI solutions that are almost right, but not quite",partly,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,It takes significant time and effort to learn ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
5,6,I am a developer by profession,45-54 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc....",15.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",Technical documentation (is generated for/by t...,20.0,"Developer, back-end",NaN,NaN,NaN,"Yes, I influenced the purchase of a substantia...",Work,12.0,5.0,4.0,6.0,2.0,10.0,3.0,7.0,8.0,14.0,NaN,12.0,5.0,13.0,10.0,9.0,1.0,4.0,6.0,2.0,15.0,NaN,Fintech,4.0,3.0,5.0,8.0,9.0,2.0,1.0,10.0,11.0,12.0,6.0,13.0,14.0,15.0,7.0,NaN,I'm not sure,I have somewhat considered changing my career ...,5.0,5.0,Ukraine,USD United States dollar,120000.0,Yes,Java;Scala,Java;Kotlin;Scala,Java;Scala,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Google Cloud;Microso...,Amazon Web Services (AWS),Amazon Web Services (AWS),NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,akka,akka,Yes,IntelliJ IDEA;Visual Studio Code,IntelliJ IDEA;Visual Studio Code,IntelliJ IDEA;Visual Studio Code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MacOS,MacOS,Azure Devops;GitHub;GitLab;Jira,GitHub;Jira,GitHub;Jira,NaN,NaN,Stack Overflow;Stack Exchange;X;YouTube;Linked...,Stack Overflow;Stack Exchange;X;YouTube;Linked...,Stack Overflow;Stack Exchange;X;YouTube;Linked...,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 10 and 15 years,"Infrequently, less than once per year","Lists of recommendations (tools, frameworks, t...",6.0,NaN,9.0,3.0,4.0,5.0,10.0,1.0,11.0,15.0,NaN,"Yes, somewhat","Rarely, almost never","Yes, I use AI tools daily",Indifferent,Somewhat distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Documen...,Predictive analytics,Deployment and monitoring,Project planning;Debugging or fixing code;Comm...,Testing code;Learning new concepts or technolo...,"AI solutions that are almost right, but not quite",No it isnt,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering;Business process automati...,NaN,AI agents have increased my productivity.;AI a...,NaN,AI agents have improved the quality of my code...,AI agents have helped me automate repetitive t...,NaN,The cost of using certain AI agent platforms i...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,My company's IT and/or InfoSec teams have stri...,NaN,NaN,NaN,NaN,NaN,NaN,GitHub Copilot,NaN,When I have ethical or security concerns about...,designing the architecture in the new domain,120000.0,7.0

In [53]:
def count_models(column):
    counts = (
        df[column]
        .dropna()
        .str.split(';')
        .explode()
        .str.strip()
        .replace(model_mapping)
        .value_counts()
    )
    return counts

In [54]:
worked = count_models("AIModelsHaveWorkedWith")
wanted = count_models("AIModelsWantToWorkWith")
admired = count_models("AIModelsAdmired")
print(worked)
print(wanted)
print(admired)

AIModelsHaveWorkedWith
OpenAI        19140
Gemini        10044
Claude         7063
DeepSeek       6211
DALL-E         4395
Llama          2941
Grok           1839
Mistral        1712
Perplexity     1250
Qwen            864
Phi-4           833
Titan           283
Command A       139
Reka             57
Name: count, dtype: int64
AIModelsWantToWorkWith
OpenAI        12541
Gemini         7535
Claude         5428
DeepSeek       4582
DALL-E         3031
Llama          2004
Grok           1429
Mistral        1288
Perplexity     1012
Qwen            669
Phi-4           629
Titan           312
Command A       155
Reka            131
Name: count, dtype: int64
AIModelsAdmired
OpenAI        11850
Gemini         6045
Claude         4767
DeepSeek       3191
DALL-E         2610
Llama          1419
Grok            955
Mistral         849
Perplexity      685
Qwen            465
Phi-4           356
Titan           121
Command A        58
Reka             35
Name: count, dtype: int64

In [62]:
columns = [
    "AIModelsHaveWorkedWith",
    "AIModelsWantToWorkWith",
    "AIModelsAdmired"
]

for col in columns:
    df_clean[col + "_Clean"] = df[col]

In [64]:
df_clean[
    [
        "AIModelsHaveWorkedWith_Clean",
        "AIModelsWantToWorkWith_Clean",
        "AIModelsAdmired_Clean"
    ]
].head(30)

,AIModelsHaveWorkedWith_Clean,AIModelsWantToWorkWith_Clean,AIModelsAdmired_Clean
0,OpenAI;DALL-E;OpenAI,NaN,NaN
1,OpenAI,OpenAI,OpenAI
2,Gemini;OpenAI,Gemini;Gemini;OpenAI,Gemini;OpenAI
3,NaN,NaN,NaN
4,OpenAI,OpenAI,OpenAI
5,NaN,NaN,NaN
6,NaN,NaN,NaN
7,OpenAI,Claude;OpenAI;OpenAI;Perplexity,OpenAI
8,NaN,NaN,NaN
9,NaN,NaN,NaN
10,Claude;OpenAI;OpenAI,Claude;OpenAI;OpenAI,Claude;OpenAI;OpenAI
11,NaN,NaN,NaN
12,OpenAI,OpenAI,OpenAI
13,NaN,NaN,NaN
14,NaN,NaN,NaN
15,Qwen;Titan;OpenAI,NaN,NaN
16,NaN,NaN,NaN
17,OpenAI,NaN,NaN
18,DeepSeek;DeepSeek;Llama;Mistral,NaN,NaN
19,NaN,NaN,NaN
20,NaN,NaN,NaN
21,NaN,NaN,NaN
22,NaN,NaN,NaN
23,OpenAI;OpenAI,NaN,NaN
24,NaN,NaN,NaN
25,OpenAI,Claude;DeepSeek;DeepSeek;Gemini;Gemini;OpenAI;...,OpenAI
26,NaN,NaN,NaN
27,NaN,NaN,NaN
28,Claude;DeepSeek;Gemini;Llama,NaN,NaN
29,Claude;OpenAI,NaN,NaN

In [ ]:
df_clean.to_csv(
    r"..\Data_out\AI_Adoption_2025_Clean.csv",
    index=False
)

In [67]:
def count_models(column):
    counts = (
        df_clean[column]
        .dropna()
        .str.split(';')
        .explode()
        .str.strip()
        .value_counts()
    )
    return counts

In [68]:
used = count_models("AIModelsHaveWorkedWith_Clean").reset_index()
used.columns = ["Model", "Count"]
used["Type"] = "Used"

wanted = count_models("AIModelsWantToWorkWith_Clean").reset_index()
wanted.columns = ["Model", "Count"]
wanted["Type"] = "Wanted"

admired = count_models("AIModelsAdmired_Clean").reset_index()
admired.columns = ["Model", "Count"]
admired["Type"] = "Admired"

In [69]:
print(df_clean.columns.tolist())

['Age', 'Country', 'Employment', 'MainBranch', 'AISelect', 'AISent', 'AIAcc', 'AIComplex', 'AIAgents', 'AI_Usage_Group', 'Sentiment_Group', 'Trust_Group', 'AI_Capability_Group', 'Agent_Adoption_Group', 'AIModelsHaveWorkedWith_Clean', 'AIModelsWantToWorkWith_Clean', 'AIModelsAdmired_Clean']

In [72]:
ai_models_summary = pd.concat(
    [used, wanted, admired],
    ignore_index=True
)

print(ai_models_summary.head(100))

         Model  Count     Type
0       OpenAI  19140     Used
1       Gemini  10044     Used
2       Claude   7063     Used
3     DeepSeek   6211     Used
4       DALL-E   4395     Used
5        Llama   2941     Used
6         Grok   1839     Used
7      Mistral   1712     Used
8   Perplexity   1250     Used
9         Qwen    864     Used
10       Phi-4    833     Used
11       Titan    283     Used
12   Command A    139     Used
13        Reka     57     Used
14      OpenAI  12541   Wanted
15      Gemini   7535   Wanted
16      Claude   5428   Wanted
17    DeepSeek   4582   Wanted
18      DALL-E   3031   Wanted
19       Llama   2004   Wanted
20        Grok   1429   Wanted
21     Mistral   1288   Wanted
22  Perplexity   1012   Wanted
23        Qwen    669   Wanted
24       Phi-4    629   Wanted
25       Titan    312   Wanted
26   Command A    155   Wanted
27        Reka    131   Wanted
28      OpenAI  11850  Admired
29      Gemini   6045  Admired
30      Claude   4767  Admired
31    DeepSeek   3191  Admired
32      DALL-E   2610  Admired
33       Llama   1419  Admired
34        Grok    955  Admired
35     Mistral    849  Admired
36  Perplexity    685  Admired
37        Qwen    465  Admired
38       Phi-4    356  Admired
39       Titan    121  Admired
40   Command A     58  Admired
41        Reka     35  Admired

In [ ]:
ai_models_summary.to_csv(
    r"..\Data_out\ai_models_summary.csv",
    index=False,
    encoding="utf-8-sig"
)