In [ ]:
import pandas as pd
df = pd.read_csv(r"..\Data_in\survey_results_public_2024.csv",low_memory=False)

In [2]:
df.info(verbose=True)

<class 'pandas.DataFrame'>
RangeIndex: 65437 entries, 0 to 65436
Data columns (total 114 columns):
 #    Column                          Dtype
---   ------                          -----
 0    ResponseId                      int64
 1    MainBranch                      str
 2    Age                             str
 3    Employment                      str
 4    RemoteWork                      str
 5    Check                           str
 6    CodingActivities                str
 7    EdLevel                         str
 8    LearnCode                       str
 9    LearnCodeOnline                 str
 10   TechDoc                         str
 11   YearsCode                       str
 12   YearsCodePro                    str
 13   DevType                         str
 14   OrgSize                         str
 15   PurchaseInfluence               str
 16   BuyNewTool                      str
 17   BuildvsBuy                      str
 18   TechEndorse                     str
 19   Country                         str
 20   Currency                        str
 21   CompTotal                       float64
 22   LanguageHaveWorkedWith          str
 23   LanguageWantToWorkWith          str
 24   LanguageAdmired                 str
 25   DatabaseHaveWorkedWith          str
 26   DatabaseWantToWorkWith          str
 27   DatabaseAdmired                 str
 28   PlatformHaveWorkedWith          str
 29   PlatformWantToWorkWith          str
 30   PlatformAdmired                 str
 31   WebframeHaveWorkedWith          str
 32   WebframeWantToWorkWith          str
 33   WebframeAdmired                 str
 34   EmbeddedHaveWorkedWith          str
 35   EmbeddedWantToWorkWith          str
 36   EmbeddedAdmired                 str
 37   MiscTechHaveWorkedWith          str
 38   MiscTechWantToWorkWith          str
 39   MiscTechAdmired                 str
 40   ToolsTechHaveWorkedWith         str
 41   ToolsTechWantToWorkWith         str
 42   ToolsTechAdmired                str
 43   NEWCollabToolsHaveWorkedWith    str
 44   NEWCollabToolsWantToWorkWith    str
 45   NEWCollabToolsAdmired           str
 46   OpSysPersonal use               str
 47   OpSysProfessional use           str
 48   OfficeStackAsyncHaveWorkedWith  str
 49   OfficeStackAsyncWantToWorkWith  str
 50   OfficeStackAsyncAdmired         str
 51   OfficeStackSyncHaveWorkedWith   str
 52   OfficeStackSyncWantToWorkWith   str
 53   OfficeStackSyncAdmired          str
 54   AISearchDevHaveWorkedWith       str
 55   AISearchDevWantToWorkWith       str
 56   AISearchDevAdmired              str
 57   NEWSOSites                      str
 58   SOVisitFreq                     str
 59   SOAccount                       str
 60   SOPartFreq                      str
 61   SOHow                           str
 62   SOComm                          str
 63   AISelect                        str
 64   AISent                          str
 65   AIBen                           str
 66   AIAcc                           str
 67   AIComplex                       str
 68   AIToolCurrently Using           str
 69   AIToolInterested in Using       str
 70   AIToolNot interested in Using   str
 71   AINextMuch more integrated      str
 72   AINextNo change                 str
 73   AINextMore integrated           str
 74   AINextLess integrated           str
 75   AINextMuch less integrated      str
 76   AIThreat                        str
 77   AIEthics                        str
 78   AIChallenges                    str
 79   TBranch                         str
 80   ICorPM                          str
 81   WorkExp                         float64
 82   Knowledge_1                     str
 83   Knowledge_2                     str
 84   Knowledge_3                     str
 85   Knowledge_4                     str
 86   Knowledge_5                     str
 87   Knowledge_6                     str
 88   Knowledge_7                     str
 89   Knowledge_8                     str
 90   Knowledge_9                     str
 91   Frequency_1                     str
 92   Frequency_2                     str
 93   Frequency_3                     str
 94   TimeSearching                   str
 95   TimeAnswering                   str
 96   Frustration                     str
 97   ProfessionalTech                str
 98   ProfessionalCloud               str
 99   ProfessionalQuestion            str
 100  Industry                        str
 101  JobSatPoints_1                  float64
 102  JobSatPoints_4                  float64
 103  JobSatPoints_5                  float64
 104  JobSatPoints_6                  float64
 105  JobSatPoints_7                  float64
 106  JobSatPoints_8                  float64
 107  JobSatPoints_9                  float64
 108  JobSatPoints_10                 float64
 109  JobSatPoints_11                 float64
 110  SurveyLength                    str
 111  SurveyEase                      str
 112  ConvertedCompYearly             float64
 113  JobSat                          float64
dtypes: float64(13), int64(1), str(100)
memory usage: 56.9 MB

In [3]:
list(df.columns)

['ResponseId',
 'MainBranch',
 'Age',
 'Employment',
 'RemoteWork',
 'Check',
 'CodingActivities',
 'EdLevel',
 'LearnCode',
 'LearnCodeOnline',
 'TechDoc',
 'YearsCode',
 'YearsCodePro',
 'DevType',
 'OrgSize',
 'PurchaseInfluence',
 'BuyNewTool',
 'BuildvsBuy',
 'TechEndorse',
 'Country',
 'Currency',
 'CompTotal',
 'LanguageHaveWorkedWith',
 'LanguageWantToWorkWith',
 'LanguageAdmired',
 'DatabaseHaveWorkedWith',
 'DatabaseWantToWorkWith',
 'DatabaseAdmired',
 'PlatformHaveWorkedWith',
 'PlatformWantToWorkWith',
 'PlatformAdmired',
 'WebframeHaveWorkedWith',
 'WebframeWantToWorkWith',
 'WebframeAdmired',
 'EmbeddedHaveWorkedWith',
 'EmbeddedWantToWorkWith',
 'EmbeddedAdmired',
 'MiscTechHaveWorkedWith',
 'MiscTechWantToWorkWith',
 'MiscTechAdmired',
 'ToolsTechHaveWorkedWith',
 'ToolsTechWantToWorkWith',
 'ToolsTechAdmired',
 'NEWCollabToolsHaveWorkedWith',
 'NEWCollabToolsWantToWorkWith',
 'NEWCollabToolsAdmired',
 'OpSysPersonal use',
 'OpSysProfessional use',
 'OfficeStackAsyncHaveWorkedWith',
 'OfficeStackAsyncWantToWorkWith',
 'OfficeStackAsyncAdmired',
 'OfficeStackSyncHaveWorkedWith',
 'OfficeStackSyncWantToWorkWith',
 'OfficeStackSyncAdmired',
 'AISearchDevHaveWorkedWith',
 'AISearchDevWantToWorkWith',
 'AISearchDevAdmired',
 'NEWSOSites',
 'SOVisitFreq',
 'SOAccount',
 'SOPartFreq',
 'SOHow',
 'SOComm',
 'AISelect',
 'AISent',
 'AIBen',
 'AIAcc',
 'AIComplex',
 'AIToolCurrently Using',
 'AIToolInterested in Using',
 'AIToolNot interested in Using',
 'AINextMuch more integrated',
 'AINextNo change',
 'AINextMore integrated',
 'AINextLess integrated',
 'AINextMuch less integrated',
 'AIThreat',
 'AIEthics',
 'AIChallenges',
 'TBranch',
 'ICorPM',
 'WorkExp',
 'Knowledge_1',
 'Knowledge_2',
 'Knowledge_3',
 'Knowledge_4',
 'Knowledge_5',
 'Knowledge_6',
 'Knowledge_7',
 'Knowledge_8',
 'Knowledge_9',
 'Frequency_1',
 'Frequency_2',
 'Frequency_3',
 'TimeSearching',
 'TimeAnswering',
 'Frustration',
 'ProfessionalTech',
 'ProfessionalCloud',
 'ProfessionalQuestion',
 'Industry',
 'JobSatPoints_1',
 'JobSatPoints_4',
 'JobSatPoints_5',
 'JobSatPoints_6',
 'JobSatPoints_7',
 'JobSatPoints_8',
 'JobSatPoints_9',
 'JobSatPoints_10',
 'JobSatPoints_11',
 'SurveyLength',
 'SurveyEase',
 'ConvertedCompYearly',
 'JobSat']

In [4]:
df.shape

(65437, 114)

In [5]:
ai_col=[col for col in df.columns if "ai" in col.lower()]
ai_col

['MainBranch',
 'AISearchDevHaveWorkedWith',
 'AISearchDevWantToWorkWith',
 'AISearchDevAdmired',
 'AISelect',
 'AISent',
 'AIBen',
 'AIAcc',
 'AIComplex',
 'AIToolCurrently Using',
 'AIToolInterested in Using',
 'AIToolNot interested in Using',
 'AINextMuch more integrated',
 'AINextNo change',
 'AINextMore integrated',
 'AINextLess integrated',
 'AINextMuch less integrated',
 'AIThreat',
 'AIEthics',
 'AIChallenges']

In [6]:
df.head(20)

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
3,4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
4,5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN
5,6,I code primarily as a hobby,Under 18 years old,"Student, full-time",NaN,Apples,NaN,Primary/elementary school,"School (i.e., University, College, etc);Online...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
6,7,"I am not primarily a developer, but I write co...",35-44 years old,"Employed, full-time",Remote,Apples,I don’t code outside of work,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Stack Overflow;Written...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN,NaN
7,8,I am learning to code,18-24 years old,"Student, full-time;Not employed, but looking f...",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Video-based Online Cou...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Difficult,NaN,NaN
8,9,I code primarily as a hobby,45-54 years old,"Employed, full-time",In-person,Apples,Hobby,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Books / Physical media;Other online resources ...,Stack Overflow;Written-based Online Courses,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN,NaN
9,10,I am a developer by profession,35-44 years old,"Independent contractor, freelancer, or self-em...",Remote,Apples,Bootstrapping a business,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",On the job training;Other online resources (e....,Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
10,11,"I used to be a developer by profession, but no...",35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Books;Written Tutorial...,...,25.0,10.0,0.0,15.0,0.0,0.0,Appropriate in length,Easy,NaN,8.0
11,12,I am a developer by profession,45-54 years old,"Employed, full-time",In-person,Apples,Hobby;School or academic work,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Books / Physical media;School (i.e., Universit...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN,NaN
12,13,I am a developer by profession,35-44 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby;Contribute to open-source projects;Profe...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;On the job training;Sch...,NaN,...,30.0,0.0,0.0,20.0,10.0,10.0,Appropriate in length,Easy,NaN,8.0
13,14,"I used to be a developer by profession, but no...",35-44 years old,"Not employed, and not looking for work",NaN,Apples,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Colleague;Other online resources (e.g., videos...",Technical documentation;Blogs;Stack Overflow;I...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN,NaN
14,15,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby;Professional development or self-paced l...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Other online resources ...,Stack Overflow;Coding sessions (live or record...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
15,16,I am a developer by profession,45-54 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby,Some college/university study without earning ...,Books / Physical media;On the job training;Oth...,Technical documentation;Books;Written Tutorial...,...,0.0,0.0,0.0,0.0,0.0,0.0,Appropriate in length,Neither easy nor difficult,NaN,5.0
16,17,I code primarily as a hobby,Under 18 years old,"Student, full-time",NaN,Apples,NaN,Primary/elementary school,Books / Physical media;Other online resources ...,Technical documentation;Written Tutorials;Stac...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
17,18,I am a developer by profession,18-24 years old,"Independent contractor, freelancer, or self-em...",Remote,Apples,Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Blogs;Coding sessions (live or recorded);How-t...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
18,19,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby;Professional development or self-paced l...,Some college/university study without earning ...,Books / Physical media;On the job training;Oth...,Technical documentation;Blogs;Books;Stack Over...,...,60.0,10.0,10.0,0.0,0.0,0.0,Appropriate in length,Easy,NaN,10.0
19,20,I am a developer by profession,35-44 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby;Professional development or self-paced l...,Some college/university study without earning ...,Books / Physical media;Other online resources ...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN,NaN

In [7]:
general_info_col=[
    "Age",
    "Country",
    "Employment",
    "MainBranch",
    "AISelect",
    "AISent",
    "AIAcc",
    "AIComplex",
 
]
for col in general_info_col:
    if col in df.columns:
        print("\n")
        print("="*50)
        print(df[col].value_counts(dropna=False).head(20))

==================================================
Age
25-34 years old       23911
35-44 years old       14942
18-24 years old       14098
45-54 years old        6249
55-64 years old        2575
Under 18 years old     2568
65 years or older       772
Prefer not to say       322
Name: count, dtype: int64


==================================================
Country
United States of America                                11095
NaN                                                      6507
Germany                                                  4947
India                                                    4231
United Kingdom of Great Britain and Northern Ireland     3224
Ukraine                                                  2672
France                                                   2110
Canada                                                   2104
Poland                                                   1534
Netherlands                                              1449
Brazil                                                   1375
Italy                                                    1341
Australia                                                1260
Spain                                                    1123
Sweden                                                   1016
Russian Federation                                        925
Switzerland                                               876
Austria                                                   791
Czech Republic                                            714
Israel                                                    604
Name: count, dtype: int64


==================================================
Employment
Employed, full-time                                                                        39041
Independent contractor, freelancer, or self-employed                                        4846
Student, full-time                                                                          4709
Employed, full-time;Independent contractor, freelancer, or self-employed                    3557
Not employed, but looking for work                                                          2341
Employed, part-time                                                                         1266
Student, full-time;Employed, part-time                                                      1115
Employed, full-time;Student, full-time                                                       897
Employed, full-time;Student, part-time                                                       839
Student, full-time;Not employed, but looking for work                                        686
Not employed, and not looking for work                                                       633
Student, part-time;Employed, part-time                                                       558
I prefer not to say                                                                          546
Retired                                                                                      525
Student, part-time                                                                           494
Independent contractor, freelancer, or self-employed;Employed, part-time                     401
Not employed, but looking for work;Independent contractor, freelancer, or self-employed      383
Student, full-time;Independent contractor, freelancer, or self-employed                      375
Student, full-time;Not employed, and not looking for work                                    311
Employed, full-time;Employed, part-time                                                      212
Name: count, dtype: int64


==================================================
MainBranch
I am a developer by profession                                                           50207
I am not primarily a developer, but I write code sometimes as part of my work/studies     6511
I am learning to code                                                                     3875
I code primarily as a hobby                                                               3334
I used to be a developer by profession, but no longer am                                  1510
Name: count, dtype: int64


==================================================
AISelect
Yes                        37662
No, and I don't plan to    14837
No, but I plan to soon      8408
NaN                         4530
Name: count, dtype: int64


==================================================
AISent
Favorable           22167
NaN                 19564
Very favorable      10848
Indifferent          8564
Unfavorable          2381
Unsure               1357
Very unfavorable      556
Name: count, dtype: int64


==================================================
AIAcc
NaN                           28135
Somewhat trust                15039
Neither trust nor distrust     9920
Somewhat distrust              8395
Highly distrust                2932
Highly trust                   1016
Name: count, dtype: int64


==================================================
AIComplex
NaN                                              28416
Good, but not great at handling complex tasks    12102
Bad at handling complex tasks                    11583
Neither good or bad at handling complex tasks     7706
Very poor at handling complex tasks               4415
Very well at handling complex tasks               1215
Name: count, dtype: int64

In [8]:
important_cols =    [
    'Age',
    'Country',
    'Employment',
    'MainBranch',
    'AISelect',
    'AISent',
    'AIAcc',
    'AIComplex',
   
]

df_clean = df[important_cols].copy()

df_clean['Age'] = df_clean['Age'].fillna('Unknown')
df_clean['Country'] = df_clean['Country'].fillna('Unknown Country')
df_clean['Employment'] = df_clean['Employment'].fillna('Unknown')
df_clean['MainBranch'] = df_clean['MainBranch'].fillna('Unknown')

for col in ['AISelect', 'AISent', 'AIAcc', 'AIComplex']:
    df_clean[col] = df_clean[col].fillna('No Response')

In [9]:
general_info_col=[
    "Age",
    "Country",
    "Employment",
    "MainBranch",
    "AISelect",
    "AISent",
    "AIAcc",
    "AIComplex",
 
]
for col in general_info_col:
    if col in df_clean.columns:
        print("\n")
        print("="*50)
        print(df_clean[col].value_counts(dropna=False).head(20))

==================================================
Age
25-34 years old       23911
35-44 years old       14942
18-24 years old       14098
45-54 years old        6249
55-64 years old        2575
Under 18 years old     2568
65 years or older       772
Prefer not to say       322
Name: count, dtype: int64


==================================================
Country
United States of America                                11095
Unknown Country                                          6507
Germany                                                  4947
India                                                    4231
United Kingdom of Great Britain and Northern Ireland     3224
Ukraine                                                  2672
France                                                   2110
Canada                                                   2104
Poland                                                   1534
Netherlands                                              1449
Brazil                                                   1375
Italy                                                    1341
Australia                                                1260
Spain                                                    1123
Sweden                                                   1016
Russian Federation                                        925
Switzerland                                               876
Austria                                                   791
Czech Republic                                            714
Israel                                                    604
Name: count, dtype: int64


==================================================
Employment
Employed, full-time                                                                        39041
Independent contractor, freelancer, or self-employed                                        4846
Student, full-time                                                                          4709
Employed, full-time;Independent contractor, freelancer, or self-employed                    3557
Not employed, but looking for work                                                          2341
Employed, part-time                                                                         1266
Student, full-time;Employed, part-time                                                      1115
Employed, full-time;Student, full-time                                                       897
Employed, full-time;Student, part-time                                                       839
Student, full-time;Not employed, but looking for work                                        686
Not employed, and not looking for work                                                       633
Student, part-time;Employed, part-time                                                       558
I prefer not to say                                                                          546
Retired                                                                                      525
Student, part-time                                                                           494
Independent contractor, freelancer, or self-employed;Employed, part-time                     401
Not employed, but looking for work;Independent contractor, freelancer, or self-employed      383
Student, full-time;Independent contractor, freelancer, or self-employed                      375
Student, full-time;Not employed, and not looking for work                                    311
Employed, full-time;Employed, part-time                                                      212
Name: count, dtype: int64


==================================================
MainBranch
I am a developer by profession                                                           50207
I am not primarily a developer, but I write code sometimes as part of my work/studies     6511
I am learning to code                                                                     3875
I code primarily as a hobby                                                               3334
I used to be a developer by profession, but no longer am                                  1510
Name: count, dtype: int64


==================================================
AISelect
Yes                        37662
No, and I don't plan to    14837
No, but I plan to soon      8408
No Response                 4530
Name: count, dtype: int64


==================================================
AISent
Favorable           22167
No Response         19564
Very favorable      10848
Indifferent          8564
Unfavorable          2381
Unsure               1357
Very unfavorable      556
Name: count, dtype: int64


==================================================
AIAcc
No Response                   28135
Somewhat trust                15039
Neither trust nor distrust     9920
Somewhat distrust              8395
Highly distrust                2932
Highly trust                   1016
Name: count, dtype: int64


==================================================
AIComplex
No Response                                      28416
Good, but not great at handling complex tasks    12102
Bad at handling complex tasks                    11583
Neither good or bad at handling complex tasks     7706
Very poor at handling complex tasks               4415
Very well at handling complex tasks               1215
Name: count, dtype: int64

In [10]:
usage_map = {
    'Yes':'AI User',
    'No, but I plan to soon':'Future User',
    "No, and I don't plan to":'Non User',
    'No Response':'No Response'
}

df_clean['AI_Usage_Group'] = df_clean['AISelect'].map(usage_map)

In [11]:
sentiment_map = {
    'Very favorable':'Positive',
    'Favorable':'Positive',
    'Indifferent':'Neutral',
    'Unsure':'Neutral',
    'Unfavorable':'Negative',
    'Very unfavorable':'Negative',
    'No Response':'No Response'
}

df_clean['Sentiment_Group'] = df_clean['AISent'].map(sentiment_map)

In [12]:
trust_map = {
    'Highly trust':'Trust',
    'Somewhat trust':'Trust',
    'Neither trust nor distrust':'Neutral',
    'Somewhat distrust':'Distrust',
    'Highly distrust':'Distrust',
    'No Response':'No Response'
}

df_clean['Trust_Group'] = df_clean['AIAcc'].map(trust_map)

In [13]:
complexity_map = {
    'Very well at handling complex tasks':'Good',
    'Good, but not great at handling complex tasks':'Good',
    'Neither good or bad at handling complex tasks':'Neutral',
    'Bad at handling complex tasks':'Poor',
    'Very poor at handling complex tasks':'Poor',
    'No Response':'No Response'
}

df_clean['AI_Capability_Group'] = df_clean['AIComplex'].map(complexity_map)

In [14]:
mainbranch_map = {
    "I am a developer by profession": "Professional Developer",

    "I am not primarily a developer, but I write code sometimes as part of my work/studies":
    "Occasional Developer",

    "I am learning to code":
    "Learning Developer",

    "I code primarily as a hobby":
    "Hobbyist",

    "I used to be a developer by profession, but no longer am":
    "Former Developer"
}

df_clean["Developer_Profile"] = (
    df_clean["MainBranch"]
    .map(mainbranch_map)
)

In [15]:
df_clean = df_clean.drop(columns=['Employment'])

In [16]:
 for col in df_clean.columns:
    print("\n" + "="*50)
    print(df_clean[col].value_counts().head(30))

==================================================
Age
25-34 years old       23911
35-44 years old       14942
18-24 years old       14098
45-54 years old        6249
55-64 years old        2575
Under 18 years old     2568
65 years or older       772
Prefer not to say       322
Name: count, dtype: int64

==================================================
Country
United States of America                                11095
Unknown Country                                          6507
Germany                                                  4947
India                                                    4231
United Kingdom of Great Britain and Northern Ireland     3224
Ukraine                                                  2672
France                                                   2110
Canada                                                   2104
Poland                                                   1534
Netherlands                                              1449
Brazil                                                   1375
Italy                                                    1341
Australia                                                1260
Spain                                                    1123
Sweden                                                   1016
Russian Federation                                        925
Switzerland                                               876
Austria                                                   791
Czech Republic                                            714
Israel                                                    604
Turkey                                                    546
Belgium                                                   526
Denmark                                                   504
Portugal                                                  470
Norway                                                    450
Romania                                                   439
Pakistan                                                  415
Iran, Islamic Republic of...                              411
China                                                     406
Mexico                                                    402
Name: count, dtype: int64

==================================================
MainBranch
I am a developer by profession                                                           50207
I am not primarily a developer, but I write code sometimes as part of my work/studies     6511
I am learning to code                                                                     3875
I code primarily as a hobby                                                               3334
I used to be a developer by profession, but no longer am                                  1510
Name: count, dtype: int64

==================================================
AISelect
Yes                        37662
No, and I don't plan to    14837
No, but I plan to soon      8408
No Response                 4530
Name: count, dtype: int64

==================================================
AISent
Favorable           22167
No Response         19564
Very favorable      10848
Indifferent          8564
Unfavorable          2381
Unsure               1357
Very unfavorable      556
Name: count, dtype: int64

==================================================
AIAcc
No Response                   28135
Somewhat trust                15039
Neither trust nor distrust     9920
Somewhat distrust              8395
Highly distrust                2932
Highly trust                   1016
Name: count, dtype: int64

==================================================
AIComplex
No Response                                      28416
Good, but not great at handling complex tasks    12102
Bad at handling complex tasks                    11583
Neither good or bad at handling complex tasks     7706
Very poor at handling complex tasks               4415
Very well at handling complex tasks               1215
Name: count, dtype: int64

==================================================
AI_Usage_Group
AI User        37662
Non User       14837
Future User     8408
No Response     4530
Name: count, dtype: int64

==================================================
Sentiment_Group
Positive       33015
No Response    19564
Neutral         9921
Negative        2937
Name: count, dtype: int64

==================================================
Trust_Group
No Response    28135
Trust          16055
Distrust       11327
Neutral         9920
Name: count, dtype: int64

==================================================
AI_Capability_Group
No Response    28416
Poor           15998
Good           13317
Neutral         7706
Name: count, dtype: int64

==================================================
Developer_Profile
Professional Developer    50207
Occasional Developer       6511
Learning Developer         3875
Hobbyist                   3334
Former Developer           1510
Name: count, dtype: int64

In [17]:
df_clean.to_csv(
    'AI_Adoption_2024_Clean.csv',
    index=False
)

In [18]:
pd.set_option('display.max_columns', None)
df.head(30)

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,BuildvsBuy,TechEndorse,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,EmbeddedHaveWorkedWith,EmbeddedWantToWorkWith,EmbeddedAdmired,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,MiscTechAdmired,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,ToolsTechAdmired,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,NEWCollabToolsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,OfficeStackSyncAdmired,AISearchDevHaveWorkedWith,AISearchDevWantToWorkWith,AISearchDevAdmired,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOHow,SOComm,AISelect,AISent,AIBen,AIAcc,AIComplex,AIToolCurrently Using,AIToolInterested in Using,AIToolNot interested in Using,AINextMuch more integrated,AINextNo change,AINextMore integrated,AINextLess integrated,AINextMuch less integrated,AIThreat,AIEthics,AIChallenges,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Knowledge_9,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I have never visited Stack Overflow or the Sta...,NaN,NaN,NaN,NaN,NaN,Yes,Very favorable,Increase productivity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,20,17,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Dynamodb;MongoDB;PostgreSQL,PostgreSQL,PostgreSQL,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Express;Next.js;Node.js;React,Express;Htmx;Node.js;React;Remix,Express;Node.js;React,NaN,NaN,NaN,NaN,NaN,NaN,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,MacOS;Windows,MacOS,NaN,NaN,NaN,Microsoft Teams;Slack,Slack,Slack,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,17.0,Agree,Disagree,Agree,Agree,Agree,Neither agree nor disagree,Disagree,Agree,Agree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,37,27,Developer Experience,NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,C#,C#,C#,Firebase Realtime Database,Firebase Realtime Database,Firebase Realtime Database,Google Cloud,Google Cloud,Google Cloud,ASP.NET CORE,ASP.NET CORE,ASP.NET CORE,Rasberry Pi,Rasberry Pi,Rasberry Pi,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,MSBuild,MSBuild,MSBuild,Visual Studio,Visual Studio,Visual Studio,Windows,Windows,NaN,NaN,NaN,Google Chat;Google Meet;Microsoft Teams;Zoom,Google Chat;Google Meet;Zoom,Google Chat;Google Meet;Zoom,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Stack Overflow B...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
3,4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,NaN,4,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Canada,NaN,NaN,C;C++;HTML/CSS;Java;JavaScript;PHP;PowerShell;...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,MongoDB;MySQL;PostgreSQL;SQLite,MongoDB;MySQL;PostgreSQL,MongoDB;MySQL;PostgreSQL,Amazon Web Services (AWS);Fly.io;Heroku,Amazon Web Services (AWS);Vercel,Amazon Web Services (AWS),jQuery;Next.js;Node.js;React;WordPress,jQuery;Next.js;Node.js;React,jQuery;Next.js;Node.js;React,Rasberry Pi,NaN,NaN,NumPy;Pandas;Ruff;TensorFlow,NaN,NaN,Docker;npm;Pip,Docker;Kubernetes;npm,Docker;npm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow,Daily or almost daily,No,NaN,Quickly finding code solutions,"No, not really",Yes,Very favorable,Increase productivity;Greater efficiency;Impro...,Somewhat trust,Bad at handling complex tasks,Learning about a codebase;Project planning;Wri...,Testing code;Committing and reviewing code;Pre...,NaN,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,NaN,No,Circulating misinformation or disinformation;M...,Don’t trust the output or answers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
4,5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,9,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Norway,NaN,NaN,C++;HTML/CSS;JavaScript;Lua;Python;Rust,C++;HTML/CSS;JavaScript;Lua;Python,C++;HTML/CSS;JavaScript;Lua;Python,PostgreSQL;SQLite,PostgreSQL;SQLite,PostgreSQL;SQLite,NaN,NaN,NaN,NaN,NaN,NaN,CMake;Cargo;Rasberry Pi,CMake;Rasberry Pi,CMake;Rasberry Pi,NaN,NaN,NaN,APT;Make;npm,APT;Make,APT;Make,Vim,Vim,Vim,Other (please specify):,NaN,GitHub Discussions;Markdown File;Obsidian;Stac...,GitHub Discussions;Markdown File;Obsidian,GitHub Discussions;Markdown File;Obsidian,Discord;Whatsapp,Discord;Whatsapp,Discord;Whatsapp,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Engage with com...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN
5,6,I code primarily as a hobby,Under 18 years old,"Student, full-time",NaN,Apples,NaN,Primary/elementary school,"School (i.e., University, College, etc);Online...",NaN,NaN,10,NaN,Student,NaN,NaN,NaN,NaN,NaN,United States of America,NaN,NaN,Bash/Shell (all shells);HTML/CSS;Java;JavaScri...,Bash/Shell (all shells);HTML/CSS;Java;JavaScri...,Bash/Shell (all shells);HTML/CSS;Java;JavaScri...,Cloud Firestore,Cloud Firestore,Cloud Firestore,Cloudflare,Cloudflare,Cloudflare,Node.js,Node.js,Node.js,Rasberry Pi,Rasberry Pi,Rasberry Pi,NaN,NaN,NaN,Docker;Homebrew;npm;Pip;pnpm,Homebrew;npm;Pip;pnpm,Homebrew;npm;Pip;pnpm,Nano;Vim;Visual Studio Code;Xcode,Nano;Vim;Visual Studio Code;Xcode,Nano;Vim;Visual Studio Code;Xcode,iOS;MacOS;Ubuntu,NaN,Markdown File,Markdown File,Markdown File,Discord,Discord,Discord,ChatGPT;GitHub Copilot;OpenAI Codex,ChatGPT;GitHub Copilot,ChatGPT;GitHub Copilot,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely",Yes,Favorable,Increase productivity;Greater efficiency;Impro...,Somewhat trust,"Good, but not great at handling complex tasks",Writing code;Debugging and getting help,Documenting code;Testing code;Committing and r...,Learning about a codebase;Project planning,NaN,Writing code;Debugging and getting help,NaN,NaN,NaN,No,Circulating misinformation or disinformation;M...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
6,7,"I am not primarily a developer, but I write co...",35-44 years old,"Employed, full-time",Remote,Apples,I don’t code outside of work,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Stack Overflow;Written...,NaN,7,7,Academic researcher,NaN,NaN,NaN,NaN,NaN,United States of America,NaN,NaN,R,R,R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RStudio,RStudio,RStudio,MacOS,MacOS,NaN,NaN,NaN,Microsoft Teams;Whatsapp,Microsoft Teams;Whatsapp,Microsoft Teams;Whatsapp,NaN,NaN,NaN,Stack Overflow,Daily or almost daily,Yes,Daily or almost daily,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN,NaN
7,8,I am learning to code,18-24 years old,"Student, full-time;Not employed, but looking f...",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Video-based Online Cou...,First-party knowledge base,1,NaN,Student,NaN,NaN,NaN,NaN,NaN,Uzbekistan,NaN,NaN,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;TypeScript,Supabase,Supabase,Supabase,Firebase;Netlify;Vercel,Vercel,Vercel,Next.js;React,Next.js;React,Next.js;React,NaN,NaN,NaN,NaN,NaN,NaN,npm;Vite;Yarn,npm;Vite,npm;Vite,Visual Studio Code,Visual Studio Code,Visual Studio Code,MacOS,MacOS,Jira,NaN,NaN,Google Meet;Telegram;Zoom,Google Meet;Telegram,Google Meet;Telegram,ChatGPT,ChatGPT,ChatGPT,Stack Overflow,Less than once per month or monthly,No,NaN,Quickly finding code solutions;Finding reliabl...,"No, not at all",Yes,Indifferent,Increase productivity;Speed up learning;Improv...,Somewhat distrust,Bad at handling complex tasks,Writing code;Debugging and getting help;Search...,Project planning;Testing code,NaN,NaN,NaN,Writing code;Debugging and getting help;Search...,NaN,NaN,Yes,Circulating misinformation or disinformation;M...,Don’t trust the output or answers;AI tools lac...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Difficult,NaN,NaN
8,9,I code primarily as a hobby,45-54 years old,"Employed, full-time",In-person,Apples,Hobby,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Books / Physical media;Other online resources ...,Stack Overflow;Written-based Online Courses,NaN,20,NaN,Academic researcher,NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,Lua,Lua,Lua,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Visual Studio Code,Visual Studio Code,Visual Studio Code,MacOS,MacOS,NaN,NaN,NaN,Skype,Skype,Skype,NaN,NaN,NaN,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Multiple times per day,Engage with community by commenting on questio...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN,NaN
9,10,I am a developer by profession,35-44 years old,"Independent contractor, freelancer, or self-em...",Remote,Apples,Bootstrapping a business,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",On the job training;Other online resources (e....,Technical documentation;Blogs;Written Tutorial...,Traditional public search engine;AI-powered se...,15,11,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Serbia,NaN,NaN,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;TypeScript,MongoDB;MySQL;PostgreSQL;Redis,MongoDB;MySQL;PostgreSQL;Redis,MongoDB;MySQL;PostgreSQL;Redis,Amazon Web Services (AWS);Digital Ocean;Fireba...,Amazon Web Services (AWS);Digital Ocean;Fireba...,Amazon Web Services (AWS);Digital Ocean;Fireba...,Express;Next.js;Node.js;React,Express;Next.js;Node.js;React,Express;Next.js;Node.js;React,NaN,NaN,NaN,NaN,NaN,NaN,npm;Webpack,npm;Webpack,npm;Webpack,Visual Studio Code,Visual Studio Code,Visual Studio Code,Windows,Windows,Jira,Jira,Jira,Discord;Google Meet;Skype;Slack,Discord;Google Meet;Skype;Slack,Discord;Google Meet;Skype;Slack,ChatGPT;Google Gemini,ChatGPT;Google Gemini,ChatGPT;Google Gemini,Stack Overflow,A few times per week,Yes,Less than once per month or monthly,Quickly finding code solutions,"Yes, somewhat",Yes,Indifferent,Increase productivity;Speed up learning,Neither trust nor distrust,Bad at handling complex tasks,Search for answers,NaN,NaN,NaN,Search for answers,NaN,NaN,NaN,I'm not sure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
10,11,"I used to be a developer by profession, but no...",35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Books;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,20,NaN,Project manager,NaN,NaN,NaN,NaN,NaN,United States of America,NaN,NaN,JavaScript;Python;Ruby,C#;Crystal;Java;JavaScript;Python;Ruby,JavaScript;Python;Ruby,Elasticsearch;MongoDB;PostgreSQL;SQLite,Elasticsearch;MongoDB;PostgreSQL;SQLite,Elasticsearch;MongoDB;PostgreSQL;SQLite,Amazon Web Services (AWS);Google Cloud,Google Cloud,Google Cloud,Node.js;React;Ruby on Rails,Django;Node.js;React;Ruby on Rails,Node.js;React;Ruby on Rails,NaN,NaN,NaN,NaN,NaN,NaN,Ansible;Docker;Kubernetes,Ansible;Docker;Kubernetes,Ansible;Docker;Kubernetes,Visual Studio Code,Visual Studio Code,Visual Studio Code,Windows;Windows Subsystem for Linux (WSL),Windows,Confluence;GitHub Discussions;Jira;Smartsheet,Confluence;GitHub Discussions;Jira,Confluence;GitHub Discussions;Jira,Discord;Google Meet;Microsoft Teams;Slack;Zoom,Discord;Google Meet;Microsoft Teams;Slack;Zoom,Discord;Google Meet;Microsoft Teams;Slack;Zoom,ChatGPT;GitHub Copilot;Google Gemini;Meta AI;V...,GitHub Copilot;Google Gemini;Visual Studio Int...,GitHub Copilot;Google Gemini;Visual Studio Int...,Stack Overflow for Teams (private knowledge sh...,A few times per week,Yes,Less than once per month or monthly,Quickly finding code solutions;Finding reliabl...,"Yes, definitely",Yes,Favorable,Increase productivity;Speed up learning;Improv...,Somewhat distrust,Neither good or bad at handling complex tasks,Learning about a codebase;Writing code;Documen...,Project planning;Testing code;Generating conte...,Committing and reviewing code;Deployment and m...,NaN,NaN,Learning about a codebase;Writing code;Documen...,NaN,NaN,No,Circulating misinformation or disinformation;M...,Don’t trust the output or answers;AI tools lac...,Yes,Individual contributor,15.0,Strongly agree,Agree,Strongly agree,Agree,Agree,Strongly agree,Agree,Neither agree nor disagree,Neither agree nor disagree,3-5 times a week,6-10 times a week,6-10 times a week,30-60 minutes a day,60-120 minutes a day,Amount of technical debt;Number of software to...,DevOps function;Automated testing;Observabilit...,Cloud only (single or multi-cloud),Internal Developer portal,Healthcare,50.0,0.0,0.0,25.0,10.0,0.0,15.0,0.0,0.0,Appropriate in length,Easy,NaN,8.0
11,12,I am a developer by profession,45-54 years old,"Employed, full-time",In-person,Apples,Hobby;School or academic work,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Books / Physical media;School (i.e., Universit...",NaN,NaN,30,25,Developer Advocate,NaN,NaN,NaN,NaN,NaN,Poland,NaN,NaN,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Power...,C#;HTML/CSS;JavaScript;PowerShell;Rust;SQL;Typ...,C#;HTML/CSS;JavaScript;PowerShell;SQL;TypeScript,Microsoft Access;Microsoft SQL Server;PostgreS...,Microsoft SQL Server;PostgreSQL;SQLite,Microsoft SQL Server;PostgreSQL;SQLite,Cloudflare,Cloudflare,Cloudflare,ASP.NET;ASP.NET CORE;Express;jQuery;Node.js;React,ASP.NET;ASP.NET CORE;Express;jQuery;Node.js;React,ASP.NET;ASP.NET CORE;Express;jQuery;Node.js;React,NaN,NaN,NaN,.NET (5+) ;.NET Framework (1.0 - 4.8);RabbitMQ...,.NET (5+) ;.NET Framework (1.0 - 4.8);RabbitMQ,.NET (5+) ;.NET Framework (1.0 - 4.8);RabbitMQ,Docker;npm;Webpack;Yarn,Docker;npm;Webpack;Yarn,Docker;npm;Webpack;Yarn,Android Studio;IntelliJ IDEA;Netbeans;Notepad+...,Notepad++;Visual Studio;Visual Studio Code,Notepad++;Visual Studio;Visual Studio Code,Windows;Windows Subsystem for Linux (WSL),Windows;Windows Subsystem for Linux (WSL),NaN,NaN,NaN,Microsoft Teams,Microsoft Teams,Microsoft Teams,NaN,NaN,NaN,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Engage with com...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN,NaN

In [19]:
columns_map = {
    "Language": [
        "LanguageHaveWorkedWith",
        "LanguageWantToWorkWith",
        "LanguageAdmired"
    ],
    "Database": [
        "DatabaseHaveWorkedWith",
        "DatabaseWantToWorkWith",
        "DatabaseAdmired"
    ],
    "Platform": [
        "PlatformHaveWorkedWith",
        "PlatformWantToWorkWith",
        "PlatformAdmired"
    ],
    "Tools": [
        "ToolsTechHaveWorkedWith",
        "ToolsTechWantToWorkWith",
        "ToolsTechAdmired"
    ],
    "CollabTools": [
        "NEWCollabToolsHaveWorkedWith",
        "NEWCollabToolsWantToWorkWith",
        "NEWCollabToolsAdmired"
    ]
}

In [20]:
def build_table(df, category, columns):
    frames = []

    for col in columns:
        if "HaveWorked" in col:
            typ = "Used"
        elif "WantToWork" in col:
            typ = "Wanted"
        else:
            typ = "Admired"

        tmp = (
            df[col]
            .dropna()
            .str.split(';')
            .explode()
            .str.strip()
            .value_counts()
            .reset_index()
        )

        tmp.columns = ["Item", "Count"]
        tmp["Category"] = category
        tmp["Type"] = typ

        frames.append(tmp)

    return pd.concat(frames, ignore_index=True)

In [22]:
all_tables = []

for category, cols in columns_map.items():
    all_tables.append(build_table(df, category, cols))

final_df = pd.concat(all_tables, ignore_index=True)

In [26]:
print(final_df.head(2000))

             Item  Count     Category     Type
0      JavaScript  37492     Language     Used
1        HTML/CSS  31816     Language     Used
2          Python  30719     Language     Used
3             SQL  30682     Language     Used
4      TypeScript  23150     Language     Used
..            ...    ...          ...      ...
535        Spyder    353  CollabTools  Admired
536        BBEdit    302  CollabTools  Admired
537         Geany    294  CollabTools  Admired
538  Code::Blocks    265  CollabTools  Admired
539     Spacemacs     93  CollabTools  Admired

[540 rows x 4 columns]

In [ ]:
final_df.to_csv(r"..\Data_out\tech_ecosystem_dashboard.csv", index=False, encoding="utf-8-sig")