In [ ]:
import pandas as pd
df = pd.read_csv(r"..\Data_in\survey_results_public_2023.csv",low_memory=False)

In [2]:
df.info(verbose=True)

<class 'pandas.DataFrame'>
RangeIndex: 89184 entries, 0 to 89183
Data columns (total 84 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   ResponseId                           89184 non-null  int64
 1   Q120                                 89184 non-null  str
 2   MainBranch                           89184 non-null  str
 3   Age                                  89184 non-null  str
 4   Employment                           87898 non-null  str
 5   RemoteWork                           73810 non-null  str
 6   CodingActivities                     73764 non-null  str
 7   EdLevel                              87973 non-null  str
 8   LearnCode                            87663 non-null  str
 9   LearnCodeOnline                      70084 non-null  str
 10  LearnCodeCoursesCert                 37076 non-null  str
 11  YearsCode                            87435 non-null  str
 12  YearsCodePro                         66136 non-null  str
 13  DevType                              76872 non-null  str
 14  OrgSize                              65043 non-null  str
 15  PurchaseInfluence                    64964 non-null  str
 16  TechList                             60851 non-null  str
 17  BuyNewTool                           83009 non-null  str
 18  Country                              87973 non-null  str
 19  Currency                             65334 non-null  str
 20  CompTotal                            48225 non-null  float64
 21  LanguageHaveWorkedWith               87140 non-null  str
 22  LanguageWantToWorkWith               80709 non-null  str
 23  DatabaseHaveWorkedWith               73435 non-null  str
 24  DatabaseWantToWorkWith               60911 non-null  str
 25  PlatformHaveWorkedWith               63628 non-null  str
 26  PlatformWantToWorkWith               51308 non-null  str
 27  WebframeHaveWorkedWith               66938 non-null  str
 28  WebframeWantToWorkWith               56741 non-null  str
 29  MiscTechHaveWorkedWith               57019 non-null  str
 30  MiscTechWantToWorkWith               46848 non-null  str
 31  ToolsTechHaveWorkedWith              77884 non-null  str
 32  ToolsTechWantToWorkWith              68315 non-null  str
 33  NEWCollabToolsHaveWorkedWith         85864 non-null  str
 34  NEWCollabToolsWantToWorkWith         76649 non-null  str
 35  OpSysPersonal use                    86557 non-null  str
 36  OpSysProfessional use                78587 non-null  str
 37  OfficeStackAsyncHaveWorkedWith       69090 non-null  str
 38  OfficeStackAsyncWantToWorkWith       53743 non-null  str
 39  OfficeStackSyncHaveWorkedWith        83439 non-null  str
 40  OfficeStackSyncWantToWorkWith        69776 non-null  str
 41  AISearchHaveWorkedWith               56328 non-null  str
 42  AISearchWantToWorkWith               46150 non-null  str
 43  AIDevHaveWorkedWith                  25904 non-null  str
 44  AIDevWantToWorkWith                  19587 non-null  str
 45  NEWSOSites                           87973 non-null  str
 46  SOVisitFreq                          87140 non-null  str
 47  SOAccount                            87852 non-null  str
 48  SOPartFreq                           66061 non-null  str
 49  SOComm                               87692 non-null  str
 50  SOAI                                 47858 non-null  str
 51  AISelect                             87973 non-null  str
 52  AISent                               61501 non-null  str
 53  AIAcc                                38594 non-null  str
 54  AIBen                                61396 non-null  str
 55  AIToolInterested in Using            32783 non-null  str
 56  AIToolCurrently Using                36137 non-null  str
 57  AIToolNot interested in Using        21069 non-null  str
 58  AINextVery different                 12661 non-null  str
 59  AINextNeither different nor similar  6599 non-null   str
 60  AINextSomewhat similar               6238 non-null   str
 61  AINextVery similar                   2621 non-null   str
 62  AINextSomewhat different             23303 non-null  str
 63  TBranch                              65768 non-null  str
 64  ICorPM                               43668 non-null  str
 65  WorkExp                              43579 non-null  float64
 66  Knowledge_1                          42535 non-null  str
 67  Knowledge_2                          41670 non-null  str
 68  Knowledge_3                          41798 non-null  str
 69  Knowledge_4                          41684 non-null  str
 70  Knowledge_5                          41527 non-null  str
 71  Knowledge_6                          41520 non-null  str
 72  Knowledge_7                          41467 non-null  str
 73  Knowledge_8                          41404 non-null  str
 74  Frequency_1                          41916 non-null  str
 75  Frequency_2                          41925 non-null  str
 76  Frequency_3                          41054 non-null  str
 77  TimeSearching                        42778 non-null  str
 78  TimeAnswering                        42629 non-null  str
 79  ProfessionalTech                     41783 non-null  str
 80  Industry                             36774 non-null  str
 81  SurveyLength                         86485 non-null  str
 82  SurveyEase                           86554 non-null  str
 83  ConvertedCompYearly                  48019 non-null  float64
dtypes: float64(3), int64(1), str(80)
memory usage: 57.2 MB

In [3]:
df.shape

(89184, 84)

In [4]:
ai_col=[col for col in df.columns if "ai" in col.lower()]
ai_col

['MainBranch',
 'AISearchHaveWorkedWith',
 'AISearchWantToWorkWith',
 'AIDevHaveWorkedWith',
 'AIDevWantToWorkWith',
 'SOAI',
 'AISelect',
 'AISent',
 'AIAcc',
 'AIBen',
 'AIToolInterested in Using',
 'AIToolCurrently Using',
 'AIToolNot interested in Using',
 'AINextVery different',
 'AINextNeither different nor similar',
 'AINextSomewhat similar',
 'AINextVery similar',
 'AINextSomewhat different']

In [5]:
pd.set_option('display.max_columns', None)
df.head(30)

,ResponseId,Q120,MainBranch,Age,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,TechList,BuyNewTool,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,AISearchHaveWorkedWith,AISearchWantToWorkWith,AIDevHaveWorkedWith,AIDevWantToWorkWith,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,SOAI,AISelect,AISent,AIAcc,AIBen,AIToolInterested in Using,AIToolCurrently Using,AIToolNot interested in Using,AINextVery different,AINextNeither different nor similar,AINextSomewhat similar,AINextVery similar,AINextSomewhat different,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,ProfessionalTech,Industry,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,I agree,None of these,18-24 years old,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;Friend or fam...,Formal documentation provided by the owner of ...,Other,18,9,"Senior Executive (C-Suite, VP, etc.)",2 to 9 employees,I have a great deal of influence,Investigate,Start a free trial;Ask developers I know/work ...,United States of America,USD\tUnited States dollar,285000.0,HTML/CSS;JavaScript;Python,Bash/Shell (all shells);C#;Dart;Elixir;GDScrip...,Supabase,Firebase Realtime Database;Supabase,Amazon Web Services (AWS);Netlify;Vercel,Fly.io;Netlify;Render,Next.js;React;Remix;Vue.js,Deno;Elm;Nuxt.js;React;Svelte;Vue.js,Electron;React Native;Tauri,Capacitor;Electron;Tauri;Uno Platform;Xamarin,Docker;Kubernetes;npm;Pip;Vite;Webpack;Yarn,Godot;npm;pnpm;Unity 3D;Unreal Engine;Vite;Web...,Vim;Visual Studio Code,Vim;Visual Studio Code,iOS;iPadOS;MacOS;Windows;Windows Subsystem for...,MacOS;Windows;Windows Subsystem for Linux (WSL),Asana;Basecamp;GitHub Discussions;Jira;Linear;...,GitHub Discussions;Linear;Notion;Trello,Cisco Webex Teams;Discord;Google Chat;Google M...,Discord;Signal;Slack;Zoom,ChatGPT,ChatGPT;Neeva AI,GitHub Copilot,GitHub Copilot,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,A few times per month or weekly,"Yes, definitely","I don't think it's super necessary, but I thin...",Yes,Indifferent,Other (please explain),Somewhat distrust,Learning about a codebase;Writing code;Debuggi...,Writing code;Committing and reviewing code,NaN,NaN,NaN,NaN,NaN,NaN,Yes,People manager,10.0,Strongly agree,Agree,Strongly agree,Agree,Agree,Agree,Agree,Strongly agree,1-2 times a week,10+ times a week,Never,15-30 minutes a day,15-30 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,285000.0
2,3,I agree,I am a developer by profession,45-54 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Formal documentation provided by the owner of ...,NaN,27,23,"Developer, back-end","5,000 to 9,999 employees",I have some influence,Given a list,Start a free trial;Ask developers I know/work ...,United States of America,USD\tUnited States dollar,250000.0,Bash/Shell (all shells);Go,Haskell;OCaml;Rust,NaN,NaN,Amazon Web Services (AWS);Google Cloud;OpenSta...,NaN,NaN,NaN,NaN,NaN,Cargo;Docker;Kubernetes;Make;Nix,Cargo;Kubernetes;Nix,Emacs;Helix,Emacs;Helix,MacOS;Other Linux-based,MacOS;Other Linux-based,Markdown File;Stack Overflow for Teams,Markdown File,Microsoft Teams;Slack;Zoom,Slack;Zoom,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Stack Overflow f...,A few times per month or weekly,Yes,Less than once per month or monthly,Neutral,NaN,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,23.0,Strongly agree,Neither agree nor disagree,Agree,Agree,Agree,Agree,Agree,Agree,6-10 times a week,6-10 times a week,3-5 times a week,30-60 minutes a day,30-60 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,250000.0
3,4,I agree,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Friend or family member;Other online...,Formal documentation provided by the owner of ...,NaN,12,7,"Developer, front-end",100 to 499 employees,I have some influence,Investigate,Start a free trial;Ask developers I know/work ...,United States of America,USD\tUnited States dollar,156000.0,Bash/Shell (all shells);HTML/CSS;JavaScript;PH...,Bash/Shell (all shells);HTML/CSS;JavaScript;Ru...,PostgreSQL;Redis,PostgreSQL;Redis,Cloudflare;Heroku,Cloudflare;Heroku,Node.js;React;Ruby on Rails;Vue.js;WordPress,Node.js;Ruby on Rails;Vue.js,NaN,NaN,Homebrew;npm;Vite;Webpack;Yarn,Homebrew;npm;Vite,IntelliJ IDEA;Vim;Visual Studio Code;WebStorm,IntelliJ IDEA;Vim;WebStorm,iOS;iPadOS;MacOS,iOS;iPadOS;MacOS,Jira,Jira,Discord;Google Meet;Microsoft Teams;Slack;Zoom,Discord;Google Meet;Slack;Zoom,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange,A few times per week,Yes,Less than once per month or monthly,"No, not really",I'm wearing of Stack Overflow using AI.,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,7.0,Strongly agree,Strongly disagree,Strongly agree,Strongly agree,Agree,Neither agree nor disagree,Agree,Agree,1-2 times a week,10+ times a week,1-2 times a week,15-30 minutes a day,30-60 minutes a day,Automated testing;Continuous integration (CI) ...,NaN,Appropriate in length,Easy,156000.0
4,5,I agree,I am a developer by profession,25-34 years old,"Employed, full-time;Independent contractor, fr...",Remote,Hobby;Contribute to open-source projects;Profe...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Online Courses or Certi...,Formal documentation provided by the owner of ...,Other;Codecademy;edX,6,4,"Developer, full-stack",20 to 99 employees,I have some influence,Investigate,Start a free trial;Ask developers I know/work ...,Philippines,PHP\tPhilippine peso,1320000.0,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;Python;Rust;TypeScript,BigQuery;Elasticsearch;MongoDB;PostgreSQL,Elasticsearch;MongoDB;PostgreSQL;Redis;Supabase,Amazon Web Services (AWS);Firebase;Heroku;Netl...,Amazon Web Services (AWS);Cloudflare;Digital O...,Express;Gatsby;NestJS;Next.js;Node.js;React,Express;NestJS;Next.js;Node.js;React;Remix;Vue.js,NaN,NaN,Docker;npm;Webpack;Yarn,Docker;npm;Yarn,Vim;Visual Studio Code,Vim;Visual Studio Code,Other (Please Specify):,Other (Please Specify):,Confluence;Jira;Notion,Confluence;Jira;Notion,Discord;Google Meet;Slack;Zoom,Discord;Google Meet;Slack;Zoom,ChatGPT,ChatGPT,NaN,NaN,Stack Overflow;Stack Exchange,A few times per week,No,NaN,Neutral,Using AI to suggest better answer to my questi...,Yes,Very favorable,Increase productivity;Greater efficiency;Speed...,Somewhat trust,Project planning;Testing code;Committing and r...,Learning about a codebase;Writing code;Documen...,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,6.0,Agree,Strongly agree,Agree,Agree,Neither agree nor disagree,Agree,Strongly agree,Agree,1-2 times a week,1-2 times a week,3-5 times a week,60-120 minutes a day,30-60 minutes a day,Microservices;Automated testing;Observability ...,Other,Appropriate in length,Neither easy nor difficult,23456.0
5,6,I agree,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Hobby;Professional development or self-paced l...,Some college/university study without earning ...,Books / Physical media;Colleague;Online Course...,Formal documentation provided by the owner of ...,Other,21,21,"Developer, back-end",100 to 499 employees,I have little or no influence,NaN,Start a free trial;Ask developers I know/work ...,United Kingdom of Great Britain and Northern I...,GBP\tPound sterling,78000.0,Bash/Shell (all shells);HTML/CSS;JavaScript;Ru...,Go;Rust,BigQuery;Cloud Firestore;PostgreSQL;Redis,NaN,Amazon Web Services (AWS);Cloudflare;Google Cloud,NaN,Angular;Express;NestJS;Node.js,NaN,NaN,NaN,Docker;Homebrew;Kubernetes;npm;pnpm;Terraform,Cargo,Helix;Neovim,NaN,Other (Please Specify):,MacOS,Jira;Markdown File;Notion;Stack Overflow for T...,NaN,Google Meet;Microsoft Teams;Slack;Zoom,NaN,ChatGPT;Google Bard AI;Neeva AI,NaN,GitHub Copilot;Tabnine,NaN,Stack Overflow,Daily or almost daily,Yes,I have never participated in Q&A on Stack Over...,"No, not at all",NaN,Yes,Favorable,Greater efficiency,Somewhat trust,Learning about a codebase;Documenting code;Tes...,Writing code;Debugging and getting help,Project planning,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,22.0,Agree,Strongly agree,Disagree,Neither agree nor disagree,Strongly disagree,Neither agree nor disagree,Disagree,Disagree,1-2 times a week,1-2 times a week,3-5 times a week,30-60 minutes a day,15-30 minutes a day,DevOps function;Microservices;Observability to...,Other,Appropriate in length,Neither easy nor difficult,96828.0
6,7,I agree,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Profe...,Some college/university study without earning ...,Friend or family member;Online Courses or Cert...,NaN,Udemy,4,3,"Developer, full-stack","1,000 to 4,999 employees",I have little or no influence,NaN,Ask developers I know/work with;Read ratings o...,United States of America,USD\tUnited States dollar,135000.0,Ada;Clojure;Elixir;Go;HTML/CSS;Java;JavaScript...,NaN,MariaDB;Microsoft SQL Server;MySQL;PostgreSQL;...,Datomic,Amazon Web Services (AWS);Digital Ocean,Vercel,AngularJS;jQuery;Node.js;Phoenix;Ruby on Rails...,NaN,RabbitMQ;Spring Framework,NaN,Bun;Cargo;Chocolatey;Docker;Homebrew;Kubernete...,NaN,Emacs;IntelliJ IDEA;RubyMine;Visual Studio Cod...,NaN,MacOS;Windows,MacOS,Jira,NaN,Slack,NaN,ChatGPT,NaN,GitHub Copilot,NaN,Stack Overflow,A few times per month or weekly,Yes,Less than once per month or monthly,Neutral,Neutral,Yes,Unfavorable,Improve accuracy in coding,Somewhat distrust,NaN,Writing code;Debugging and getting help,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,4.0,Strongly agree,Agree,Neither agree nor disagree,Neither agree nor disagree,Agree,Agree,Agree,Neither agree nor disagree,1-2 times a week,3-5 times a week,1-2 times a week,Less than 15 minutes a day,15-30 minutes a day,Microservices;Automated testing;Continuous int...,"Information Services, IT, Software Development...",Appropriate in length,Easy,135000.0
7,8,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Online Courses or Certi...,Formal documentation provided by the owner of ...,Codecademy;edX,5,3,"Developer, full-stack",10 to 19 employees,I have some influence,Investigate,Start a free trial;Ask developers I know/work ...,United States of America,USD\tUnited States dollar,80000.0,Go;HTML/CSS;JavaScript;Python;Rust;SQL;TypeScript,Elixir;Go;Julia;Python;R;Rust;Scala;SQL;TypeSc...,Dynamodb;MongoDB;MySQL;Redis;SQLite,BigQuery;Cockroachdb;DuckDB;Elasticsearch;Mong...,Amazon Web Services (AWS);Fly.io;Netlify;Vercel,Amazon Web Services (AWS);Digital Ocean;Fly.io...,Angular;Express;Next.js;Node.js;React,Deno;FastAPI;Fastify;Flask;NestJS;Next.js;Node...,NumPy;Pandas;Scikit-Learn;Tauri;TensorFlow,.NET MAUI;Apache Kafka;Apache Spark;Hugging Fa...,Ansible;Cargo;Docker;Homebrew;Make;npm;Pip;pnp...,Cargo;Dagger;Docker;Homebrew;Kubernetes;Make;n...,DataGrip;IPython;Neovim;Vim;Visual Studio Code,IPython;Neovim;RStudio;Visual Studio Code,MacOS;Ubuntu;Windows,MacOS;Ubuntu;Windows,Markdown File;Notion,Markdown File;Notion,Microsoft Teams,Discord,Bing AI;ChatGPT;Google Bard AI,ChatGPT;Neeva AI;Perplexity AI,GitHub Copilot,GitHub Copilot,Stack Overflow;Stack Exchange;Collectives on S...,Daily or almost daily,Yes,A few times per month or weekly,"Yes, somewhat",NaN,Yes,Favorable,Increase productivity;Speed up learning,Somewhat distrust,Project planning;Writing code;Documenting code...,Project planning;Writing code;Debugging and ge...,NaN,NaN,NaN,NaN,NaN,NaN,Yes,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60-120 minutes a day,30-60 minutes a day,None of these,Financial Services,NaN,NaN,80000.0
8,9,I agree,"I am not primarily a developer, but I write co...",45-54 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Contribute to open-source projects,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Online Courses or Certification;On the job tra...,Formal documentation provided by the owner of ...,Udemy;Pluralsight,20,15,System administrator,100 to 499 employees,I have some influence,Given a list,Start a free trial;Ask developers I know/work ...,Finland,EUR European Euro,60000.0,C#;JavaScript;PowerShell;Ruby;TypeScript,C#;Ruby;Rust;TypeScript,MariaDB;Microsoft SQL Server;MySQL;PostgreSQL;...,MariaDB;Microsoft SQL Server;PostgreSQL;SQLite,Digital Ocean;Microsoft Azure;Netlify,Digital Ocean;Microsoft Azure;Netlify,ASP.NET CORE;Next.js;React;Ruby on Rails,ASP.NET CORE;Qwik;Ruby on Rails;Svelte,.NET (5+),.NET (5+),Chocolatey;Docker;Homebrew;MSBuild;npm;NuGet;p...,Homebrew;pnpm;Vite,Neovim;Visual Studio Code,Neovim;Visual Studio Code,MacOS;Ubuntu,Ubuntu;Windows;Windows Subsystem for Linux (WSL),Azure Devops;Microsoft Lists;Microsoft Planner,Azure Devops,Discord;Microsoft Teams;Slack,Discord;Microsoft Teams,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange,A few times per month or weekly,Yes,I have never participated in Q&A on Stack Over...,Neutral,To suggest solutions in alternative language f...,Yes,Very favorable,Increase productivity,Somewhat trust,Learning about a codebase;Writing code;Documen...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,64254.0
9,10,I agree,I am a developer by profession,25-34 years old,"Not employed, but looking for work",NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Online Courses or Certi...,Formal documentation provided by the owner of ...,edX;Udemy;Pluralsight;Coursera;Udacity,6,NaN,"Developer, full-stack",NaN,NaN,Investigate,Start a free trial;Research companies that hav...,India,NaN,NaN,HTML/CSS;Java;JavaScript;Python;SQL;TypeScript,HTML/CSS;JavaScript;TypeScript,Cloud Firestore;MongoDB;MySQL;PostgreSQL;SQLite,Cloud Firestore;Firebase Realtime Database;Mon...,Amazon Web Services (AWS);Firebase;Google Clou...,Cloudflare;Firebase;Google Cloud;IBM Cloud Or ...,Angular;Express;NestJS;React,Deno;Express;FastAPI;Fastify;NestJS;Qwik;React...,NaN,NaN,Docker;npm;Vite;Webpack;Yarn,Docker;npm;Podman;Vite;Webpack;Yarn,Visual Studio Code,Visual Studio Code,Fedora;Other Linux-based;Ubuntu;Windows;Window...,Fedora;Other Linux-based;Red Hat;Windows;Windo...,Asana;Markdown File;Miro;Notion;Redmine;Trello,Asana;Markdown File;Miro;Notion;Redmine;Trello,Discord;Google Chat;Google Meet;Slack;Telegram,Discord;Google Chat;Google Meet;Telegram,Bing AI;ChatGPT,Bing AI;ChatGPT;Google Bard AI,AWS CodeWhisperer;GitHub Copilot;Tabnine,AWS CodeWhisperer;GitHub Copilot,Stack Overflow;Stack Exchange,A few times per week,Yes,Less than once per month or monthly,Neutral,AI could assist solving communication issues p...,Yes,Indifferent,Other (please explain);Increase productivity;G...,Neither trust nor distrust,Learning about a codebase;Documenting code;Com...,Writing code;Debugging and getting help,Project planning;Testing code;Deployment and m...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN
10,11,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Friend or family member...,Formal documentation provided by the owner of ...,NaN,14,3,"Developer, desktop or enterprise applications",100 to 499 employees,I have little or no influence,NaN,Start a free trial;Visit developer communities...,United States of America,USD\tUnited States dollar,NaN,C#;C++;HTML/CSS;JavaScript;Python,Python,MongoDB,Firebase Realtime Database,Amazon Web Services (AWS),NaN,ASP.NET CORE;Flask;Vue.js,NaN,.NET (5+) ;.NET Framework (1.0 - 4.8),NaN,MSBuild;NuGet;Pip;Visual Studio Solution,NaN,Jupyter Notebook/JupyterLab;Visual Studio Code,Jupyter Notebook/JupyterLab;Visual Studio Code,Windows,Windows,NaN,NaN,Discord;Microsoft Teams;Slack,NaN,Bing AI;ChatGPT;Google Bard AI;WolframAlpha,NaN,NaN,NaN,Stack Overflow;Stack Exchange,A few times per week,No,NaN,"No, not really",I think AI might be helpful sort of as a searc...,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,3.0,Disagree,Strongly agree,Neither agree nor disagree,Disagree,Disagree,Agree,Agree,Disagree,1-2 times a week,1-2 times a week,6-10 times a week,30-60 minutes a day,60-120 minutes a day,Automated testing;Continuous integration (CI) ...,Other,Appropriate in length,Neither easy nor difficult,NaN
11,12,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Online Courses or Certification;Other online r...,Formal documentation provided by the owner of ...,NaN,10,9,"Developer, full-stack",100 to 499 employees,I have a great deal of influence,Investigate,Start a free trial;Ask developers I know/work ...,Australia,AUD\tAustralian dollar,118000.0,C#;HTML/CSS;JavaScript;Kotlin;PowerShell;Pytho...,C#;HTML/CSS;JavaScript;SQL;TypeScript,Cosmos DB;Microsoft SQL Server;MySQL;Redis,Microsoft SQL Server;PostgreSQL,Digital Ocean;Microsoft Azure;Netlify,Microsoft Azure;Netlify,ASP.NET CORE;Node.js;Vue.js,Nuxt.js;Qwik;Solid.js;Svelte;Vue.js,.NET (5+),.NET (5+) ;Flutter,Docker;Gradle;npm;NuGet;Vite;Webpack,npm;pnpm;Vite,Android Studio;Notepad++;Visual Studio Code,Notepad++;Visual Studio Code,MacOS,Windows,Azure Devops,NaN,Microsoft Teams;Zoom,Microsoft Teams,ChatGPT,ChatGPT,GitHub Copilot,GitHub Copilot,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,Less than once per month or monthly,"Yes, somewhat",NaN,Yes,Favorable,Increase productivity;Greater efficiency;Impro...,Somewhat trust,NaN,Writing code;Testing code,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,78003.0

In [6]:
general_info_col=[
    "Age",
    "Country",
    "MainBranch",
    "AISelect",
    "AISent",
    "AIBen",
    "AIComplex",



]
for col in general_info_col:
    if col in df.columns:
        print("\n")
        print("="*50)
        print(df[col].value_counts(dropna=False).head(20))

==================================================
Age
25-34 years old       33247
35-44 years old       20532
18-24 years old       17931
45-54 years old        8334
Under 18 years old     4128
55-64 years old        3392
65 years or older      1171
Prefer not to say       449
Name: count, dtype: int64


==================================================
Country
United States of America                                18647
Germany                                                  7328
India                                                    5625
United Kingdom of Great Britain and Northern Ireland     5552
Canada                                                   3507
France                                                   2933
Poland                                                   2435
Netherlands                                              2383
Australia                                                2078
Brazil                                                   2042
Italy                                                    1835
Spain                                                    1834
Sweden                                                   1641
NaN                                                      1211
Switzerland                                              1149
Russian Federation                                       1094
Czech Republic                                           1072
Austria                                                  1033
Israel                                                    921
Belgium                                                   888
Name: count, dtype: int64


==================================================
MainBranch
I am a developer by profession                                                           67237
I am not primarily a developer, but I write code sometimes as part of my work/studies     8954
I am learning to code                                                                     4961
I code primarily as a hobby                                                               4960
I used to be a developer by profession, but no longer am                                  1861
None of these                                                                             1211
Name: count, dtype: int64


==================================================
AISelect
Yes                        39042
No, and I don't plan to    26221
No, but I plan to soon     22710
NaN                         1211
Name: count, dtype: int64


==================================================
AISent
Favorable           29863
NaN                 27683
Very favorable      17050
Indifferent         10147
Unsure               2471
Unfavorable          1698
Very unfavorable      272
Name: count, dtype: int64


==================================================
AIBen
NaN                           27788
Somewhat trust                24128
Neither trust nor distrust    18837
Somewhat distrust             13330
Highly distrust                3350
Highly trust                   1751
Name: count, dtype: int64

In [7]:
important_cols =    [
     "Age",
    "Country",
    "MainBranch",
    "AISelect",
    "AISent",
    "AIBen"

]

df_clean = df[important_cols].copy()
df_clean['Country'] = df_clean['Country'].fillna('Unknown Country')

df_clean['AISelect'] = df_clean['AISelect'].fillna('No Response')

df_clean['AISent'] = df_clean['AISent'].fillna('No Response')

df_clean['AIBen'] = df_clean['AIBen'].fillna('No Response')

In [8]:
usage_map = {
    'Yes':'AI User',
    'No, but I plan to soon':'Future User',
    "No, and I don't plan to":'Non User',
    'No Response':'No Response'
}

df_clean['AI_Usage_Group'] = (
    df_clean['AISelect']
    .map(usage_map)
)

In [9]:
sentiment_map = {
    'Very favorable':'Positive',
    'Favorable':'Positive',

    'Indifferent':'Neutral',
    'Unsure':'Neutral',

    'Unfavorable':'Negative',
    'Very unfavorable':'Negative',

    'No Response':'No Response'
}

df_clean['Sentiment_Group'] = (
    df_clean['AISent']
    .map(sentiment_map)
)

In [10]:
trust_map = {
    'Highly trust':'Trust',
    'Somewhat trust':'Trust',

    'Neither trust nor distrust':'Neutral',

    'Somewhat distrust':'Distrust',
    'Highly distrust':'Distrust',

    'No Response':'No Response'
}

df_clean['Trust_Group'] = (
    df_clean['AIBen']
    .map(trust_map)
)

In [11]:
mainbranch_map = {
    "I am a developer by profession":
        "Professional Developer",

    "I am not primarily a developer, but I write code sometimes as part of my work/studies":
        "Occasional Developer",

    "I am learning to code":
        "Learning Developer",

    "I code primarily as a hobby":
        "Hobbyist",

    "I used to be a developer by profession, but no longer am":
        "Former Developer",

    "None of these":
        "Other"
}

df_clean["Developer_Profile"] = (
    df_clean["MainBranch"]
    .map(mainbranch_map)
)

In [12]:
 for col in df_clean.columns:
    print("\n" + "="*50)
    print(df_clean[col].value_counts().head(30))

==================================================
Age
25-34 years old       33247
35-44 years old       20532
18-24 years old       17931
45-54 years old        8334
Under 18 years old     4128
55-64 years old        3392
65 years or older      1171
Prefer not to say       449
Name: count, dtype: int64

==================================================
Country
United States of America                                18647
Germany                                                  7328
India                                                    5625
United Kingdom of Great Britain and Northern Ireland     5552
Canada                                                   3507
France                                                   2933
Poland                                                   2435
Netherlands                                              2383
Australia                                                2078
Brazil                                                   2042
Italy                                                    1835
Spain                                                    1834
Sweden                                                   1641
Unknown Country                                          1211
Switzerland                                              1149
Russian Federation                                       1094
Czech Republic                                           1072
Austria                                                  1033
Israel                                                    921
Belgium                                                   888
Turkey                                                    881
Ukraine                                                   873
Denmark                                                   850
Romania                                                   829
Portugal                                                  749
Norway                                                    732
Finland                                                   726
New Zealand                                               672
China                                                     657
Greece                                                    631
Name: count, dtype: int64

==================================================
MainBranch
I am a developer by profession                                                           67237
I am not primarily a developer, but I write code sometimes as part of my work/studies     8954
I am learning to code                                                                     4961
I code primarily as a hobby                                                               4960
I used to be a developer by profession, but no longer am                                  1861
None of these                                                                             1211
Name: count, dtype: int64

==================================================
AISelect
Yes                        39042
No, and I don't plan to    26221
No, but I plan to soon     22710
No Response                 1211
Name: count, dtype: int64

==================================================
AISent
Favorable           29863
No Response         27683
Very favorable      17050
Indifferent         10147
Unsure               2471
Unfavorable          1698
Very unfavorable      272
Name: count, dtype: int64

==================================================
AIBen
No Response                   27788
Somewhat trust                24128
Neither trust nor distrust    18837
Somewhat distrust             13330
Highly distrust                3350
Highly trust                   1751
Name: count, dtype: int64

==================================================
AI_Usage_Group
AI User        39042
Non User       26221
Future User    22710
No Response     1211
Name: count, dtype: int64

==================================================
Sentiment_Group
Positive       46913
No Response    27683
Neutral        12618
Negative        1970
Name: count, dtype: int64

==================================================
Trust_Group
No Response    27788
Trust          25879
Neutral        18837
Distrust       16680
Name: count, dtype: int64

==================================================
Developer_Profile
Professional Developer    67237
Occasional Developer       8954
Learning Developer         4961
Hobbyist                   4960
Former Developer           1861
Other                      1211
Name: count, dtype: int64

In [13]:
df_clean.to_csv(
    'AI_Adoption_2023_Clean.csv',
    index=False
)

In [15]:

pd.set_option('display.max_columns', None)
df.head(30)

,ResponseId,Q120,MainBranch,Age,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,TechList,BuyNewTool,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,AISearchHaveWorkedWith,AISearchWantToWorkWith,AIDevHaveWorkedWith,AIDevWantToWorkWith,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,SOAI,AISelect,AISent,AIAcc,AIBen,AIToolInterested in Using,AIToolCurrently Using,AIToolNot interested in Using,AINextVery different,AINextNeither different nor similar,AINextSomewhat similar,AINextVery similar,AINextSomewhat different,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,ProfessionalTech,Industry,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,I agree,None of these,18-24 years old,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;Friend or fam...,Formal documentation provided by the owner of ...,Other,18,9,"Senior Executive (C-Suite, VP, etc.)",2 to 9 employees,I have a great deal of influence,Investigate,Start a free trial;Ask developers I know/work ...,United States of America,USD\tUnited States dollar,285000.0,HTML/CSS;JavaScript;Python,Bash/Shell (all shells);C#;Dart;Elixir;GDScrip...,Supabase,Firebase Realtime Database;Supabase,Amazon Web Services (AWS);Netlify;Vercel,Fly.io;Netlify;Render,Next.js;React;Remix;Vue.js,Deno;Elm;Nuxt.js;React;Svelte;Vue.js,Electron;React Native;Tauri,Capacitor;Electron;Tauri;Uno Platform;Xamarin,Docker;Kubernetes;npm;Pip;Vite;Webpack;Yarn,Godot;npm;pnpm;Unity 3D;Unreal Engine;Vite;Web...,Vim;Visual Studio Code,Vim;Visual Studio Code,iOS;iPadOS;MacOS;Windows;Windows Subsystem for...,MacOS;Windows;Windows Subsystem for Linux (WSL),Asana;Basecamp;GitHub Discussions;Jira;Linear;...,GitHub Discussions;Linear;Notion;Trello,Cisco Webex Teams;Discord;Google Chat;Google M...,Discord;Signal;Slack;Zoom,ChatGPT,ChatGPT;Neeva AI,GitHub Copilot,GitHub Copilot,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,A few times per month or weekly,"Yes, definitely","I don't think it's super necessary, but I thin...",Yes,Indifferent,Other (please explain),Somewhat distrust,Learning about a codebase;Writing code;Debuggi...,Writing code;Committing and reviewing code,NaN,NaN,NaN,NaN,NaN,NaN,Yes,People manager,10.0,Strongly agree,Agree,Strongly agree,Agree,Agree,Agree,Agree,Strongly agree,1-2 times a week,10+ times a week,Never,15-30 minutes a day,15-30 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,285000.0
2,3,I agree,I am a developer by profession,45-54 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Formal documentation provided by the owner of ...,NaN,27,23,"Developer, back-end","5,000 to 9,999 employees",I have some influence,Given a list,Start a free trial;Ask developers I know/work ...,United States of America,USD\tUnited States dollar,250000.0,Bash/Shell (all shells);Go,Haskell;OCaml;Rust,NaN,NaN,Amazon Web Services (AWS);Google Cloud;OpenSta...,NaN,NaN,NaN,NaN,NaN,Cargo;Docker;Kubernetes;Make;Nix,Cargo;Kubernetes;Nix,Emacs;Helix,Emacs;Helix,MacOS;Other Linux-based,MacOS;Other Linux-based,Markdown File;Stack Overflow for Teams,Markdown File,Microsoft Teams;Slack;Zoom,Slack;Zoom,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Stack Overflow f...,A few times per month or weekly,Yes,Less than once per month or monthly,Neutral,NaN,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,23.0,Strongly agree,Neither agree nor disagree,Agree,Agree,Agree,Agree,Agree,Agree,6-10 times a week,6-10 times a week,3-5 times a week,30-60 minutes a day,30-60 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,250000.0
3,4,I agree,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Friend or family member;Other online...,Formal documentation provided by the owner of ...,NaN,12,7,"Developer, front-end",100 to 499 employees,I have some influence,Investigate,Start a free trial;Ask developers I know/work ...,United States of America,USD\tUnited States dollar,156000.0,Bash/Shell (all shells);HTML/CSS;JavaScript;PH...,Bash/Shell (all shells);HTML/CSS;JavaScript;Ru...,PostgreSQL;Redis,PostgreSQL;Redis,Cloudflare;Heroku,Cloudflare;Heroku,Node.js;React;Ruby on Rails;Vue.js;WordPress,Node.js;Ruby on Rails;Vue.js,NaN,NaN,Homebrew;npm;Vite;Webpack;Yarn,Homebrew;npm;Vite,IntelliJ IDEA;Vim;Visual Studio Code;WebStorm,IntelliJ IDEA;Vim;WebStorm,iOS;iPadOS;MacOS,iOS;iPadOS;MacOS,Jira,Jira,Discord;Google Meet;Microsoft Teams;Slack;Zoom,Discord;Google Meet;Slack;Zoom,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange,A few times per week,Yes,Less than once per month or monthly,"No, not really",I'm wearing of Stack Overflow using AI.,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,7.0,Strongly agree,Strongly disagree,Strongly agree,Strongly agree,Agree,Neither agree nor disagree,Agree,Agree,1-2 times a week,10+ times a week,1-2 times a week,15-30 minutes a day,30-60 minutes a day,Automated testing;Continuous integration (CI) ...,NaN,Appropriate in length,Easy,156000.0
4,5,I agree,I am a developer by profession,25-34 years old,"Employed, full-time;Independent contractor, fr...",Remote,Hobby;Contribute to open-source projects;Profe...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Online Courses or Certi...,Formal documentation provided by the owner of ...,Other;Codecademy;edX,6,4,"Developer, full-stack",20 to 99 employees,I have some influence,Investigate,Start a free trial;Ask developers I know/work ...,Philippines,PHP\tPhilippine peso,1320000.0,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;Python;Rust;TypeScript,BigQuery;Elasticsearch;MongoDB;PostgreSQL,Elasticsearch;MongoDB;PostgreSQL;Redis;Supabase,Amazon Web Services (AWS);Firebase;Heroku;Netl...,Amazon Web Services (AWS);Cloudflare;Digital O...,Express;Gatsby;NestJS;Next.js;Node.js;React,Express;NestJS;Next.js;Node.js;React;Remix;Vue.js,NaN,NaN,Docker;npm;Webpack;Yarn,Docker;npm;Yarn,Vim;Visual Studio Code,Vim;Visual Studio Code,Other (Please Specify):,Other (Please Specify):,Confluence;Jira;Notion,Confluence;Jira;Notion,Discord;Google Meet;Slack;Zoom,Discord;Google Meet;Slack;Zoom,ChatGPT,ChatGPT,NaN,NaN,Stack Overflow;Stack Exchange,A few times per week,No,NaN,Neutral,Using AI to suggest better answer to my questi...,Yes,Very favorable,Increase productivity;Greater efficiency;Speed...,Somewhat trust,Project planning;Testing code;Committing and r...,Learning about a codebase;Writing code;Documen...,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,6.0,Agree,Strongly agree,Agree,Agree,Neither agree nor disagree,Agree,Strongly agree,Agree,1-2 times a week,1-2 times a week,3-5 times a week,60-120 minutes a day,30-60 minutes a day,Microservices;Automated testing;Observability ...,Other,Appropriate in length,Neither easy nor difficult,23456.0
5,6,I agree,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Hobby;Professional development or self-paced l...,Some college/university study without earning ...,Books / Physical media;Colleague;Online Course...,Formal documentation provided by the owner of ...,Other,21,21,"Developer, back-end",100 to 499 employees,I have little or no influence,NaN,Start a free trial;Ask developers I know/work ...,United Kingdom of Great Britain and Northern I...,GBP\tPound sterling,78000.0,Bash/Shell (all shells);HTML/CSS;JavaScript;Ru...,Go;Rust,BigQuery;Cloud Firestore;PostgreSQL;Redis,NaN,Amazon Web Services (AWS);Cloudflare;Google Cloud,NaN,Angular;Express;NestJS;Node.js,NaN,NaN,NaN,Docker;Homebrew;Kubernetes;npm;pnpm;Terraform,Cargo,Helix;Neovim,NaN,Other (Please Specify):,MacOS,Jira;Markdown File;Notion;Stack Overflow for T...,NaN,Google Meet;Microsoft Teams;Slack;Zoom,NaN,ChatGPT;Google Bard AI;Neeva AI,NaN,GitHub Copilot;Tabnine,NaN,Stack Overflow,Daily or almost daily,Yes,I have never participated in Q&A on Stack Over...,"No, not at all",NaN,Yes,Favorable,Greater efficiency,Somewhat trust,Learning about a codebase;Documenting code;Tes...,Writing code;Debugging and getting help,Project planning,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,22.0,Agree,Strongly agree,Disagree,Neither agree nor disagree,Strongly disagree,Neither agree nor disagree,Disagree,Disagree,1-2 times a week,1-2 times a week,3-5 times a week,30-60 minutes a day,15-30 minutes a day,DevOps function;Microservices;Observability to...,Other,Appropriate in length,Neither easy nor difficult,96828.0
6,7,I agree,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Profe...,Some college/university study without earning ...,Friend or family member;Online Courses or Cert...,NaN,Udemy,4,3,"Developer, full-stack","1,000 to 4,999 employees",I have little or no influence,NaN,Ask developers I know/work with;Read ratings o...,United States of America,USD\tUnited States dollar,135000.0,Ada;Clojure;Elixir;Go;HTML/CSS;Java;JavaScript...,NaN,MariaDB;Microsoft SQL Server;MySQL;PostgreSQL;...,Datomic,Amazon Web Services (AWS);Digital Ocean,Vercel,AngularJS;jQuery;Node.js;Phoenix;Ruby on Rails...,NaN,RabbitMQ;Spring Framework,NaN,Bun;Cargo;Chocolatey;Docker;Homebrew;Kubernete...,NaN,Emacs;IntelliJ IDEA;RubyMine;Visual Studio Cod...,NaN,MacOS;Windows,MacOS,Jira,NaN,Slack,NaN,ChatGPT,NaN,GitHub Copilot,NaN,Stack Overflow,A few times per month or weekly,Yes,Less than once per month or monthly,Neutral,Neutral,Yes,Unfavorable,Improve accuracy in coding,Somewhat distrust,NaN,Writing code;Debugging and getting help,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,4.0,Strongly agree,Agree,Neither agree nor disagree,Neither agree nor disagree,Agree,Agree,Agree,Neither agree nor disagree,1-2 times a week,3-5 times a week,1-2 times a week,Less than 15 minutes a day,15-30 minutes a day,Microservices;Automated testing;Continuous int...,"Information Services, IT, Software Development...",Appropriate in length,Easy,135000.0
7,8,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Online Courses or Certi...,Formal documentation provided by the owner of ...,Codecademy;edX,5,3,"Developer, full-stack",10 to 19 employees,I have some influence,Investigate,Start a free trial;Ask developers I know/work ...,United States of America,USD\tUnited States dollar,80000.0,Go;HTML/CSS;JavaScript;Python;Rust;SQL;TypeScript,Elixir;Go;Julia;Python;R;Rust;Scala;SQL;TypeSc...,Dynamodb;MongoDB;MySQL;Redis;SQLite,BigQuery;Cockroachdb;DuckDB;Elasticsearch;Mong...,Amazon Web Services (AWS);Fly.io;Netlify;Vercel,Amazon Web Services (AWS);Digital Ocean;Fly.io...,Angular;Express;Next.js;Node.js;React,Deno;FastAPI;Fastify;Flask;NestJS;Next.js;Node...,NumPy;Pandas;Scikit-Learn;Tauri;TensorFlow,.NET MAUI;Apache Kafka;Apache Spark;Hugging Fa...,Ansible;Cargo;Docker;Homebrew;Make;npm;Pip;pnp...,Cargo;Dagger;Docker;Homebrew;Kubernetes;Make;n...,DataGrip;IPython;Neovim;Vim;Visual Studio Code,IPython;Neovim;RStudio;Visual Studio Code,MacOS;Ubuntu;Windows,MacOS;Ubuntu;Windows,Markdown File;Notion,Markdown File;Notion,Microsoft Teams,Discord,Bing AI;ChatGPT;Google Bard AI,ChatGPT;Neeva AI;Perplexity AI,GitHub Copilot,GitHub Copilot,Stack Overflow;Stack Exchange;Collectives on S...,Daily or almost daily,Yes,A few times per month or weekly,"Yes, somewhat",NaN,Yes,Favorable,Increase productivity;Speed up learning,Somewhat distrust,Project planning;Writing code;Documenting code...,Project planning;Writing code;Debugging and ge...,NaN,NaN,NaN,NaN,NaN,NaN,Yes,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60-120 minutes a day,30-60 minutes a day,None of these,Financial Services,NaN,NaN,80000.0
8,9,I agree,"I am not primarily a developer, but I write co...",45-54 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Contribute to open-source projects,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Online Courses or Certification;On the job tra...,Formal documentation provided by the owner of ...,Udemy;Pluralsight,20,15,System administrator,100 to 499 employees,I have some influence,Given a list,Start a free trial;Ask developers I know/work ...,Finland,EUR European Euro,60000.0,C#;JavaScript;PowerShell;Ruby;TypeScript,C#;Ruby;Rust;TypeScript,MariaDB;Microsoft SQL Server;MySQL;PostgreSQL;...,MariaDB;Microsoft SQL Server;PostgreSQL;SQLite,Digital Ocean;Microsoft Azure;Netlify,Digital Ocean;Microsoft Azure;Netlify,ASP.NET CORE;Next.js;React;Ruby on Rails,ASP.NET CORE;Qwik;Ruby on Rails;Svelte,.NET (5+),.NET (5+),Chocolatey;Docker;Homebrew;MSBuild;npm;NuGet;p...,Homebrew;pnpm;Vite,Neovim;Visual Studio Code,Neovim;Visual Studio Code,MacOS;Ubuntu,Ubuntu;Windows;Windows Subsystem for Linux (WSL),Azure Devops;Microsoft Lists;Microsoft Planner,Azure Devops,Discord;Microsoft Teams;Slack,Discord;Microsoft Teams,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange,A few times per month or weekly,Yes,I have never participated in Q&A on Stack Over...,Neutral,To suggest solutions in alternative language f...,Yes,Very favorable,Increase productivity,Somewhat trust,Learning about a codebase;Writing code;Documen...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,64254.0
9,10,I agree,I am a developer by profession,25-34 years old,"Not employed, but looking for work",NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Online Courses or Certi...,Formal documentation provided by the owner of ...,edX;Udemy;Pluralsight;Coursera;Udacity,6,NaN,"Developer, full-stack",NaN,NaN,Investigate,Start a free trial;Research companies that hav...,India,NaN,NaN,HTML/CSS;Java;JavaScript;Python;SQL;TypeScript,HTML/CSS;JavaScript;TypeScript,Cloud Firestore;MongoDB;MySQL;PostgreSQL;SQLite,Cloud Firestore;Firebase Realtime Database;Mon...,Amazon Web Services (AWS);Firebase;Google Clou...,Cloudflare;Firebase;Google Cloud;IBM Cloud Or ...,Angular;Express;NestJS;React,Deno;Express;FastAPI;Fastify;NestJS;Qwik;React...,NaN,NaN,Docker;npm;Vite;Webpack;Yarn,Docker;npm;Podman;Vite;Webpack;Yarn,Visual Studio Code,Visual Studio Code,Fedora;Other Linux-based;Ubuntu;Windows;Window...,Fedora;Other Linux-based;Red Hat;Windows;Windo...,Asana;Markdown File;Miro;Notion;Redmine;Trello,Asana;Markdown File;Miro;Notion;Redmine;Trello,Discord;Google Chat;Google Meet;Slack;Telegram,Discord;Google Chat;Google Meet;Telegram,Bing AI;ChatGPT,Bing AI;ChatGPT;Google Bard AI,AWS CodeWhisperer;GitHub Copilot;Tabnine,AWS CodeWhisperer;GitHub Copilot,Stack Overflow;Stack Exchange,A few times per week,Yes,Less than once per month or monthly,Neutral,AI could assist solving communication issues p...,Yes,Indifferent,Other (please explain);Increase productivity;G...,Neither trust nor distrust,Learning about a codebase;Documenting code;Com...,Writing code;Debugging and getting help,Project planning;Testing code;Deployment and m...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN
10,11,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Friend or family member...,Formal documentation provided by the owner of ...,NaN,14,3,"Developer, desktop or enterprise applications",100 to 499 employees,I have little or no influence,NaN,Start a free trial;Visit developer communities...,United States of America,USD\tUnited States dollar,NaN,C#;C++;HTML/CSS;JavaScript;Python,Python,MongoDB,Firebase Realtime Database,Amazon Web Services (AWS),NaN,ASP.NET CORE;Flask;Vue.js,NaN,.NET (5+) ;.NET Framework (1.0 - 4.8),NaN,MSBuild;NuGet;Pip;Visual Studio Solution,NaN,Jupyter Notebook/JupyterLab;Visual Studio Code,Jupyter Notebook/JupyterLab;Visual Studio Code,Windows,Windows,NaN,NaN,Discord;Microsoft Teams;Slack,NaN,Bing AI;ChatGPT;Google Bard AI;WolframAlpha,NaN,NaN,NaN,Stack Overflow;Stack Exchange,A few times per week,No,NaN,"No, not really",I think AI might be helpful sort of as a searc...,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,3.0,Disagree,Strongly agree,Neither agree nor disagree,Disagree,Disagree,Agree,Agree,Disagree,1-2 times a week,1-2 times a week,6-10 times a week,30-60 minutes a day,60-120 minutes a day,Automated testing;Continuous integration (CI) ...,Other,Appropriate in length,Neither easy nor difficult,NaN
11,12,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Online Courses or Certification;Other online r...,Formal documentation provided by the owner of ...,NaN,10,9,"Developer, full-stack",100 to 499 employees,I have a great deal of influence,Investigate,Start a free trial;Ask developers I know/work ...,Australia,AUD\tAustralian dollar,118000.0,C#;HTML/CSS;JavaScript;Kotlin;PowerShell;Pytho...,C#;HTML/CSS;JavaScript;SQL;TypeScript,Cosmos DB;Microsoft SQL Server;MySQL;Redis,Microsoft SQL Server;PostgreSQL,Digital Ocean;Microsoft Azure;Netlify,Microsoft Azure;Netlify,ASP.NET CORE;Node.js;Vue.js,Nuxt.js;Qwik;Solid.js;Svelte;Vue.js,.NET (5+),.NET (5+) ;Flutter,Docker;Gradle;npm;NuGet;Vite;Webpack,npm;pnpm;Vite,Android Studio;Notepad++;Visual Studio Code,Notepad++;Visual Studio Code,MacOS,Windows,Azure Devops,NaN,Microsoft Teams;Zoom,Microsoft Teams,ChatGPT,ChatGPT,GitHub Copilot,GitHub Copilot,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,Less than once per month or monthly,"Yes, somewhat",NaN,Yes,Favorable,Increase productivity;Greater efficiency;Impro...,Somewhat trust,NaN,Writing code;Testing code,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,78003.0

In [16]:
columns_map = {
    "Language": [
        "LanguageHaveWorkedWith",
        "LanguageWantToWorkWith"
    ],
    "Database": [
        "DatabaseHaveWorkedWith",
        "DatabaseWantToWorkWith"
    ],
    "Platform": [
        "PlatformHaveWorkedWith",
        "PlatformWantToWorkWith"
    ],
    "Tools": [
        "ToolsTechHaveWorkedWith",
        "ToolsTechWantToWorkWith"
    ],
     "AITools": [
        "AISearchHaveWorkedWith",
        "AISearchWantToWorkWith"
    ],

    "CollabTools": [
        "NEWCollabToolsHaveWorkedWith",
        "NEWCollabToolsWantToWorkWith"
    ]
}

In [19]:
def build_table(df, category, columns):
    frames = []

    for col in columns:
        if "HaveWorked" in col:
            typ = "Used"
        else:
            typ = "Wanted"
        

        tmp = (
            df[col]
            .dropna()
            .str.split(';')
            .explode()
            .str.strip()
            .value_counts()
            .reset_index()
        )

        tmp.columns = ["Item", "Count"]
        tmp["Category"] = category
        tmp["Type"] = typ

        frames.append(tmp)

    return pd.concat(frames, ignore_index=True)

In [20]:
all_tables = []

for category, cols in columns_map.items():
    all_tables.append(build_table(df, category, cols))

final_df = pd.concat(all_tables, ignore_index=True)

In [21]:
print(final_df.head(2000))

           Item  Count     Category    Type
0    JavaScript  55711     Language    Used
1      HTML/CSS  46396     Language    Used
2        Python  43158     Language    Used
3           SQL  42623     Language    Used
4    TypeScript  34041     Language    Used
..          ...    ...          ...     ...
417       Geany    446  CollabTools  Wanted
418       Micro    402  CollabTools  Wanted
419    TextMate    337  CollabTools  Wanted
420        Nova    226  CollabTools  Wanted
421       condo    114  CollabTools  Wanted

[422 rows x 4 columns]

In [ ]:
final_df.to_csv(r"..\Data_out\tech_ecosystem_dashboard.csv", index=False, encoding="utf-8-sig")